### ISSUE TITLE
Tipos de virtualización: foro

### ISSUE THREAD

**Issue by JJ** [IV-GII/GII-2013#1]
¿Qué tipo de virtualización es la más adecuada para: alojar varios clientes en un sólo servidor, crear un sistema efiiciente de web + middleware + base de datos, un sistema de prueba de software e integración continua? Responder y razonar.

**Comment by rafaelgonz** [comment]
1.  alojar varios clientes en un sólo servidor -> Virtualización plena, ya que virtualiza todos los aspectos de un ordenador ejecutando sistemas operativos, por lo que los clientes podrían ser alojados en un solo servidor.
2.  crear un sistema eficiente de web + middleware + base de datos -> Virtualización de aplicaciones, empaquetando estas aplicaciones  aislándolas del sistema operativo, funcionando estas sea el SO que sea.
3.  un sistema de prueba de software e integración continua -> Virtualización de entornos de desarrollo, ya que permite probar el software tal y como los clientes lo usarán en el futuro, siendo este tipo de virtualización creada para esta función específicamente.

**Comment by JoSeF267** [comment]
1.alojar varios clientes en un sólo servidor : Virtualización completa ya que el usuario puede trabajar en el servidor sin tener en cuenta a los demás usuarios y tener sus programas propietarios.

2.crear un sistema eficiente de web + middleware + base de datos : Virtualización de aplicaciones ,ya que podremos tener las aplicaciones que deseemos y usarla independientemente del resto

3.sistema de prueba de software e integración continua : Virtualización de entornos de desarrollo nos permite hacer pruebas en las maquinas casi real como seria una de producción.

**Comment by josecolella** [comment]
1. El tipo de virtualización mas adecuada para alojar clientes varios clientes en un servidor sería virtualización plena, donde se comparten los recursos del sistema entre varios usuarios. Ademas cada cliente esta aislado, donde es independiente de los otros, que significa que la actividad en un cliente no afectará al otro cliente.
2. El tipo de virtualización mas adecuada para crear un sistema eficiente de web + middleware + base de datos sería la virtualización de aplicaciones ya que encapsula las dependencias y requisitos del software del sistema operativo del cual se ejecuta. Esta aislado en un contenedor que actúa independientemente del SO.
3. El tipo de virtualización mas adecuada para un sistema de prueba de software e integración continua es la virtualización de entornos de desarrollo, ya que este tipo de virtualización permite el desarrollo de aplicaciones en entornos aislados que permiten gestionar versiones y dependencias de la aplicación.

**Comment by torresj** [comment]
1. Alojar varios clientes en un sólo servidor: Se debe usar una  virtualización plena o completa ya que ésta permite     crear varias instancias que pueden ejecutarse al mismo tiempo. Estas instancias serían dependientes unas de las otras y por ello sería las más adecuada para varios clientes en un mismo servidor.
2. Crear un sistema eficiente de web + middleware + base de datos: En este caso deberíamos usar una virtualización de aplicaciones. De esta forma podríamos separar las aplicaciones, teniendolas aisladas del resto del sistema operativo (Sea cual sea el que se ejecute).
3. Un sistema de prueba de software e integración continua: Para probar software la virtualizacion mas apropiada es la virtualización de entornos de desarrollo que esta pensada precisamente para poder crear y probar software en las mismas condiciones que se va a usar, simulando las condiciones casi reales de las maquinas en las que se usará ese software.

**Comment by R-R-R-R-1** [comment]
1. Alojar varios clientes en un sólo servidor: La virtualización completa ha demostrado ser muy exitosa para compartir un sistema informático entre múltiples usuarios y para el aislamiento de los usuarios entre sí (y desde el programa de control). Por ello creo que es la más recomendada.
2. Crear un sistema eficiente de web + middleware + base de datos: Sin duda, como mis compañeros han indicado, la virtualización de aplicaciones es la más idónea en este caso. Así mantendríamos una independencia con el SO, y permitiríamos que las aplicaciones se ejecutaran en diversos entornos aunque no se ajuste a la aplicación.
3. Un sistema de prueba de software e integración continua: Para la prueba de software e integración continua, lo mejor es una virtualización de entornos de desarrollo, ya que nos permite probar una aplicación en diferentes versiones de forma rápida y de forma muy fiel con la realidad.

**Comment by javiercollado** [comment]
Alojar varios clientes en un sólo servidor: 
    En este caso lo que queremos es dar servicio a diferentes usuarios independientes, así que lo mejor es la virtualización plena. Ya que así es como si cada usuario tuviera una maquina independiente. Permitiendo así una configuración adaptada a cada cliente.

Crear un sistema eficiente de web + middleware + base de datos: 
    En esta ocasión creo que la mejor opción es la virtualización de aplicaciones. Ya que así se ejecutará en un entorno aislado, lo que permitirá mayor eficiencia.

Un sistema de prueba de software e integración continua:
    En este caso la virtualización necesaria es “Virtualización de entornos de desarrollo”. Ya que lo que queremos es probar las aplicaciones y este método nos permite reproducir de la manera lo mas fiel posible el entorno de producción.

**Comment by rafacruiz** [comment]
1. Alojar varios clientes en un sólo servidor, la virtualización más adecuada para este tipo de características es la de tipo plena, ya que simula un hardware que permite ejecutar un sistema operativo, ahorrar en recursos y compartirlos,  utilizarse de modo aislado al resto.
2. Crear un sistema eficiente de web + middleware + base de datos, para estas características la mejor virtualización es la de aplicación. Se trabaja con contenedores Web ya que tiene un gran impacto en la productividad y flexibilidad.
3. Un sistema de prueba de software e integración continúa, utilizamos virtualización de entornos de desarrollo con el cual podemos reproducir de forma muy real y rápida los entornos de producción. También permite con una sola orden probar diferentes versiones de una misma aplicación.

**Comment by pedroag** [comment]
1. Para alojar varios clientes en un servidor, es preferible utilizar virtualización plena ya que cada cliente va a utilizar de manera aislada todos los componentes del servidor.
2. Para web + middleware + base de datos, utilizaría virtualización de aplicaciones para diferenciarlas de todo el sistema operativo.
3. Para un sistema de prueba de software e integración continua, evidentemente se usaría la virtualizacion de entornos de desarrollo, por ejemplo para probar una aplicación en diferentes versiones con una sola orden.

**Comment by franvalverde** [comment]
1. alojar varios clientes en un sólo servidor, la más adecuada es la virtualización plena donde los clientes están aislados y pueden compartir recursos.  
2. crear un sistema eficiente de web + middleware + base de datos, la más adecuada es la virtualización de aplicaciones ya empaqueta aplicaciones de forma que se ejecuten en un entorno que las aísla del resto del sistema operativo. 
3. un sistema de prueba de software e integración continua, la más adecuada es la virtualización de  entornos de desarrollo donde imitan el comportamiento que tendría un entorno que usaran los clientes.

**Comment by melero90** [comment]
1. Alojar varios clientes en un sólo servidor: El tipo de virtualización para este caso sería la virtualización plena ya que al haber múltiples usuarios necesitamos proporcionarles a cada uno de ellos una máquina virtual completa de forma independiente.
2. Crear un sistema eficiente de web + middleware + base de datos: En este caso la virtualización de aplicaciones ya que empaqueta aplicaciones de forma que se ejecuten en un entorno que las aísla del resto del sistema operativo, es decir, el usuario es capaz de ejecutar en su ordenador una aplicación que realmente no está instalada en su equipo.
3. Un sistema de prueba de software e integración continua: Utilizaría virtualización de entornos de desarrollo ya que trata de reproducir entornos de producción de la forma más fiel posible.

**Comment by jcastilloprez** [comment]
1. Alojar varios clientes en un sólo servidor: La virtualización plena ya que esta virtualización permite a los diferentes usuarios utilizar el mismo sistema operativo pero cada usuario tendría su propio entorno sin pisar los entornos de los demás usuarios. 
2. Crear un sistema eficiente de web + middleware + base de datos: La virtualización de aplicaciones porque esta nos permite separar las aplicaciones que nosotros queramos del resto del sistema operativo y trabajar con ellas independientemente de donde se ejecuten. 
3. Un sistema de prueba de software e integración continua: La virtualización de entornos de desarrollo ya que esta nos va a permitir probar este software en condiciones iguales a donde se va a utilizar el software.

**Comment by fllodrab** [comment]
1) Alojar varios clientes en un sólo servidor: La virtualización plena ya que esta virtualización permite a los diferentes usuarios utilizar el mismo sistema operativo pero cada usuario tendría su propio entorno sin pisar los entornos de los demás usuarios. 

2) Crear un sistema eficiente de web + middleware + base de datos: La virtualización de aplicaciones porque esta nos permite separar las aplicaciones que nosotros queramos del resto del sistema operativo y trabajar con ellas independientemente de donde se ejecuten. 

3) Un sistema de prueba de software e integración continua: La virtualización de entornos de desarrollo ya que esta nos va a permitir probar este software en condiciones iguales a donde se va a utilizar el software.

**Comment by germaaan** [comment]
1. Alojar varios clientes en un solo servidor: usaría virtualización plena, porque el virtualizar completamente un ordenador que pueda ejecutar sistemas operativos, nos permite compartir fácilmente el servidor entre todos los usuarios, teniendo cada uno su propia máquina virtual en la que podría trabajar con total libertad sin que esto afectara a las máquinas del resto de clientes que usen ese mismo servidor.
2. Crear un sistema eficiente de web + middleware + base de datos: usaría virtualización de aplicaciones, porque la clave es conseguir un sistema eficiente en el que usaremos varias aplicaciones, así lo mejor es que las aplicaciones se ejecuten en un entorno aislado del resto de sistema operativo, evitando así posibles errores por la interacción con el mismo.
3. Un sistema de prueba de software e integración continúa: usaría virtualización de entornos de desarrollo, ya que este tipo de virtualización está ideado para estas situaciones, el desarrollo de software, donde constantemente se está probando e integrando los últimos cambios hechos en el mismo, comprobando como responderían al ser usado en un entorno de producción.

**Comment by franciscomanuel** [comment]
1.- Para alojar varios clientes en un solo servidor usaría la virtualización plena ya que nos permite virtualizar todos los aspectos de un ordenador, así se comparte el sistema entre los distintos clientes y permite aislarlos los unos de los otros.

2.- La virtualización que usaría para crear un sistema eficiente de web+middleware+base de datos sería la virtualización de aplicaciones ya que nos permitiría empaquetar estas aplicaciones para que se ejecuten en un entorno que las aísle del resto del sistema operativo.

3.- La virtualización más adecuada para un sistema de prueba de software e integración continua es la virtualización de entornos de desarrollo ya que nos permite reproducir de la forma más fiable posible entornos de producción.

**Comment by elmendacorp** [comment]
En el caso de tener varios clientes, si lo que quieren usar es un sistema operativo como tal con la simple gestión que realiza el sistema operativo y un acceso de escritorio virtual seria suficiente. En cambio si queremos un total aislamiento una virtualización total haría que el usuario tuviera una maquina plena. El único inconveniente que esto me plantea es que como usuarios tal vez no hagan uso pleno de las características del servidor como haría un alojamiento web, por lo que tal vez al usar una virtualización plena estemos desaprovechando el rendimiento del sistema, con lo que me plantearía una virtualicación a nivel de aplicación que nos proporcionaría el aislamiento que buscamos a la vez que se utiliza el sistema con sus características completas.

Para crear un servidor web de alojamiento y uso de aplicaciones en este caso la solución histórica parece ser la mas eficaz, como el los casos de las empresas de hosting que sobre un sistema ya virtualizado montan a varios usuarios limitando su acceso al sistema y los recursos, pero de algún modo el usuario sigue teniendo cierto acceso, creo que este caso seria una virtualizacion parcial. En este caso si tenemos un servidor para aplicaciones lo cierto es que teniendo un sistema pleno necesitamos que la comunicación entre los programas tales como la base de datos. Puede que una virtualizacion de aplicación limite esta comunicación, pero en el caso de que no también seria una buena opción.

En este caso la opción es clara y es una virtualizacion del entorno de desarrollo, o lo que podríamos llamar una servidor de pre-producción, con caracteristicas similares al escenario final y que si falla sea fácilmente replicable.

**Comment by oskyar** [comment]
**1. Alojar varios clientes en un sólo servidor:** La virtualización **plena** es la más adecuada debido a que los usuarios podrán tener un sistema totalmente aislados de los demás, pudiendo configurar el sistema operativo totalmente a sus necesidades.

**2. Crear un sistema eficiente de web + middleware + base de datos:** Diría que la virtualización de **aplicaciones**, el usuario es capaz de ejecutar en su ordenador una aplicación que realmente no está instalada en su equipo. Esta aplicación se descargará bajo demanda desde un servidor en la red, que suministrará el paquete que contiene la aplicación y todo el entorno y configuraciones necesarias para su ejecución, y se podrá usar de manera aislada e independientemente del SO que tenga el sistema.

**3. Un sistema de prueba de software e integración continua:** Ni que decir tiene que sería la virtualización de **entornos de desarrollo**, ya que ésta permite reproducir de la forma más fiel posible un entorno de producción (lo que ve el cliente/usuario). Y permitiendo también probar una aplicación en diferentes versiones de manera sencilla.

**Comment by SergioMGamarra** [comment]
1. Alojar varios clientes en un sólo servidor: La virtualización más adecuada será la virtualización plena, ya que permitirá a los usuarios de dicho servidor tener sistemas totalmente aislados del resto de usuarios, pudiendo así personalizarlo a sus necesidades.
2. Crear un sistema eficiente de web + middleware + base de datos: La virtualización más adecuada será la virtualización de aplicaciones, ya que permite crear paquetes de aplicaciones, personalizando las peticiones del cliente. Además es la virtualización más eficiente para este tipo de requisitos.
3. Un sistema de prueba de software e integración continua: : La virtualización más adecuada será la virtualización de entornos de desarrollo, ya que pretende simular de la forma mas fiel posible un entorno de producción, lo que nos permite hacer pruebas reales sin riesgos.

**Comment by antonioguirola** [comment]
1.- Para alojar varios clientes en un mismo servidor lo más recomendable es la virtualización plena, permitiendo que cada cliente establezca la configuración del sistema operativo que más le interese en cada momento y asilando unos clientes de otros.

2.- En el caso de web+middleware+BD lo más indicado es utilizar virtualización a nivel de aplicaciones, de esta forma podemos empaquetar el software necesario y usarlo de manera aislada al sistema operativo, permitiendo que el paquete funcione independientemente de cuál se esté usando.

3.- Para un sistema de prueba de software e integración continua lo más indicado es emplear virtualización de entornos de desarrollo, los cuales permiten simular entornos de producción y realizar pruebas sobre ellos, de maneras que podemos estudiar cómo se comporta un sistema antes de desplegarlo en un sistema real.

**Comment by PSanchezR** [comment]
1) Alojar varios clientes en un solo servidor: Se debería utilizar preferentemente una virtualización plena para que cada usuario pueda disponer de una máquina independiente que no interfiera en las de los demás usuarios.

2) Crear un sistema eficiente de web, middleware y bbdd: En este caso el tipo de virtualización a utilizar sería la de aplicaciones que mantendría cada uno de estos software aislados de forma independiente para así tener un mejor funcionamiento y que un fallo en cualquiera de ellos no afectara a los demás.

3) Sistema de prueba de software e integración continua: Para este caso se debe utilizar la virtualización de entornos de desarrollo ya que esta especialmente diseñada para esta función, puesto que reproduce los entornos de producción de manera perfecta.

**Comment by STiago** [comment]
- Alojar varios clientes en un solo servidor: para ello usaría la virtualización plena puesto que los componentes del servidor van a ser usados por cada cliente de forma aislada.
- Crear un sistema eficiente de web + middleware + base datos: la virtualización más apropiada sería la de nivel de aplicaciones ya que podemos empaquetar dicho software aislándolo, además de que permite su funcionamiento independiente ya que así permite mayor eficiencia.
- Sistema de prueba de software e integración continua: en mi opinión, lo más apropiado es usar virtualización de entornos de desarrollo, puesto que nos permite probarlo en iguales condiciones, es decir, permite probarlo en el desarrollo donde se integran los últimos cambios ;y probarlo también en iguales condiciones en el entorno donde va a ser usado dicho software.

**Comment by javierGaliana** [comment]
Alojar varios clientes en un servidor.

Para alojar varios clientes en un servidor se podría utilizar una virtualización a nivel de sistema operativo. Con esto conseguimos que varios usuarios tengan su propio espacio, es decir, estén aislados del resto de usuarios gracias a que el kernel lo permite. Además del aislamiento también provee de  gestión de recursos para limitar el impacto entre distintas jaulas. Una de las características a tener en cuenta es que el SO no se puede cambiar por ejemplo si el nativo es Linux y en una jaula queremos instalar un SO de Microsoft. Todas tienen que tener el SO igual que el nativo.

Crear un sistema eficiente de web+middleware+base de datos.

Para poder hacer que dicha aplicación sea accesible desde cualquier dispositivo la mejor opción sería la virtualización de aplicaciones. Teniendo virtualizada la aplicación tendríamos encapsulado dentro todo el entorno necesario para poder lanzarla y mediante http podría conectarse con nuestro sistema.

Sistema de prueba de software e integración continua.

Por medio de virtualización de entornos de desarrollo podemos crear una reproducción de nuestro entorno y hacer pruebas. En caso de problemas con nuestro software no comprometemos la estabilidad de nuestro sistema ya que es una copia donde estamos trabajando y podemos eliminarla sin mayor coste y sufrimiento.

**Comment by jmanday** [comment]
1. Para alojar varios clientes en un servidor utilizaríamos una virtualización plena, ya que este tipo nos proporcionaría el mecanismo para poder virtualizar todos los aspectos de la máquina anfitriona, de forma que cada cliente que trabaje en el servidor podrá disponer de todos los recursos de los que dispone la máquina invitada.
2. Para crear un sistema web + middleware + base de datos utilizaría la virtualización de aplicaciones, ya que de este modo podríamos empaquetar todas las aplicaciones y poder ejecutarla en cualquier entorno, desde un navegador.
3. Para un sistema de prueba de software e integración contínua utilizría la virtualización de entornos de desarrollo, ya que se dispondría de un servidor de desarrollo que puede ser alterado, poder garantizar que los cambios aparecen en los trabajos de los diferentes desarrolladores, de manera que se pueda comprobar el correcto funcionamiento del conjunto, antes de que se fusionen todos los aspectos del trabajo.

**Comment by jpm88** [comment]
1. Alojar varios clientes en un servidor: Se utilizaría virtualización plena, puesto que todos los componentes del servidor serán utilizados por los clientes y con la virtualización plena se virtualizan todos los aspectos.
2. Crear un sistema efiiciente de web + middleware + base de datos: Se utilizaría la virtualización de aplicaciones, ya que empaqueta todas las aplicaciones para que se puedan ejecutar independientemente del sistema opeartivo o de cualquier software.
3. Sistema de prueba de software e integración continua: Se utilizaría virtualización de entornos de desarrollo puesto que se podrán realizar pruebas sin comprometer la integridad del sistema ya que se realiza una copia totalmente independiente del original, siendo posible modificarla a voluntad sin peligro.

**Comment by josemlp91** [comment]
Comparto la opinión de mis compañeros,

Para alojar varios clientes en un sólo servidor, visualización plena,  que facilita mayor  control del sistema a los usuarios y permite  aislarlos los unos de otros.

Para crear un sistema eficiente de web + middleware + base de datos, virtualización de aplicaciones, por permitir encapsular software y hacer que se ejecute independientemente a la plataformas, dando la opción de cambiar rápidamente de plataforma si vemos que ese cambio mejora el rendimiento.

Para un sistema de prueba de software e integración continua, virtualización de entornos de desarrollo, pudiendo simular como se comportaría en un entorno de producción pero sin asumir riesgos en el entorno real.

**Comment by JaviRubio** [comment]
¿Qué tipo de virtualización es la más adecuada para: alojar varios clientes en un sólo servidor, crear un sistema eficiente de web + middleware + base de datos, un sistema de prueba de software e integración continua? Responder y razonar.

Caso 1:Varios clientes en un servidor

La solución mas adecuada  es la virtualización plena, ya que nos permite mantener a varios clientes dándole a cada uno la sensación de que dispone de una maquina solo para el, y con la ventaja añadida de que los problemas que pueda tener un cliente no afecten al resto.

Caso 2:Sistema con web,middleware y base de datos

En este caso lo mas conveniente es virtualizar las aplicaciones, ya que es el tipo de virtualización que menos penaliza el rendimiento, y nos permite aislarlas de la plataforma en particular donde trabajemos, haciéndolas multiplaforma.

Caso 3:Sistema de prueba de software e integración continua
Aquí lo mas adecuado es virtualizar el entorno de desarrollo,ya que nos permite realizar las pruebas que necesitemos sin comprometer el entorno de pruebas y que nos garantizaría la capacidad de poder integrar los cambios que hagan los diferentes desarrolladores

**Comment by juandavarju** [comment]
Para varios clientes en un mismo servidor creo que la mejor solución sería la virtualización plena, ya que cada cliente puede usar los recursos del servidor y trabajar con ellos de una forma aislada.

Para un sistema web+middleware+ bd sería mejor la virtualización de aplicaciones, ya que así cada aplicación se podría separar del SO y trabajar con ella de forma aislada.

Para un sistema de prueba de software e integración continua la mejor opción sería virtualizar el entorno de desarrollo. De esta forma podemos hacer todas las pruebas que queramos sin tener que ponerla en el sistema real.
