### ISSUE TITLE
Ejercicio 11 (SaaS)

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#10]
¿A qué se refiere el ejercicio 11?¿hay que comentar ejemplos de Software as a service?

**Comment by josecolella** [comment]
@torresj Yo lo que hice fue hablar sobre que cosas que usamos hoy en dia que siguen los principios de SaaS. Creo que eso es lo que quiere.

**Comment by torresj** [comment]
Osea poner ejemplos actuales como pueder el webmail o escritorio remoto o cosas asi?

**Comment by josecolella** [comment]
SI...eso son los ejemplos que use yo...

**Comment by JJ** [comment]
Efectivamente.

2013/10/9 Jose Miguel Colella notifications@github.com

> SI...eso son los ejemplos que use yo...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/10#issuecomment-26010486
> .

## 

JJ

**Comment by torresj** [comment]
Perfecto, muchas gracias
