### ISSUE TITLE
Error VirtualBox

### ISSUE THREAD

**Issue by josemlp91** [IV-GII/GII-2013#100]
Tras un cierre inesperado de VirtualBox, virtualizando UbuntuServer esto es lo que me encuentro al arrancar:

![](http://pix.toile-libre.org/upload/original/1389445441.png)

Después de reinstalar VirtualBox por completo el problema persiste.

```
sudo apt-get purge virtualbox
sudo apt-get autoremove
sudo apt-get install virtualbox
```

He buscado soluciones y la más "interesante":

[ttps://bbs.archlinux.org/viewtopic.php?id=130581](https://bbs.archlinux.org/viewtopic.php?id=130581)

![](http://pix.toile-libre.org/upload/original/1389445690.png)

Este es el resultado:

![](http://pix.toile-libre.org/upload/original/1389445761.png)

**Comment by JJ** [comment]
pacman es el programa para instalación de paquetes de archlinux; evidentemente, en otras distros te aparece el verdadero pacman. Podías por lo menos haberte movido algo antes de que te comieran los fantasmas.

**Comment by torresj** [comment]
Jajajajajajaja y yo que no entendía nada del issue. Ahora entiendo...

**Comment by josemlp91** [comment]
La verdad que me he reído mucho, cuando lo vi  no sabia si era una broma (o una señal para que me pusiera más las pilas.)  Bueno a ver si consigo resucitar mi VirtualBox.

**Comment by JJ** [comment]
Ponedlo en Twitter y echamos unas risas, venga...

**Comment by josemlp91** [comment]
jaja, venga voy.
