### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by franvalverde** [IV-GII/GII-2013#101]
Repositorio --> https://github.com/franvalverde/Practica3
Documentación --> https://github.com/franvalverde/Practica3/blob/master/README.md

**Comment by JJ** [comment]
En general, correcta, pero la representación gráfica usando líneas no es la adecuada (debería ser barras) y los resultados son más o menos obvios: más núcleos y memoria, más peticiones concurrentes. Debeŕias haber justificado el uso de 50 peticiones concurrentes (son muchas peticiones concurrentes) y haber apuntado no a maximizar las prestaciones sino a minimizar los recursos para un nivel de prestaciones deseado determinado.
