### ISSUE TITLE
Problema con contenedores y blobs en Azure

### ISSUE THREAD

**Issue by fllodrab** [IV-GII/GII-2013#103]
Cuando ejecuto la orden `azure storage container create taper` me sale el siguiente error 

![screenshoterror](https://dl.dropboxusercontent.com/s/z3uruziqa70sm3w/Error1.png)

Lo mismo pasa cuando intento crear un blob con `azure storage container create images -p blob`.

Tanto la clave primaria para la cuenta de almacenamiento como el nombre estan exportados y también están grabados en el archivo .profile.

![screenshotvirt8_2](https://dl.dropboxusercontent.com/s/0kmjuah3v1zvhtx/Virt8_2.png)

¿A qué se debe dicho error?. He buscado en la documentación de windows azure pero no saco nada en claro.

Gracias de antemano.

**Comment by JJ** [comment]
Es ACCESS_KEY no ACCOUNT_KEY. A veces hay que usar copy & paste.

**Comment by fllodrab** [comment]
Cierto, intento evitar el copy&paste para luego recordar mejor los comandos aunque luego pasan estas cosas. Muchas gracias
