### ISSUE TITLE
Entrega práctica 3

### ISSUE THREAD

**Issue by PSanchezR** [IV-GII/GII-2013#105]
Enlace a la práctica 3 :https://github.com/PSanchezR/practica3
Documentación:  https://github.com/PSanchezR/practica3/blob/master/README.md

**Comment by JJ** [comment]
Si hubieras usado Azure, por ejemplo, te habría sido más fácil instalar la máquina virtual, también KVM. De esta forma tienes que tardar un buen rato en instalar las máquinas virtuales. No sé qué quieres presentar, pero un diagrama de tarta no es el adecuado. Es curioso que los hipervisores influyan tanto en las prestaciones y además que lo hagan de forma diferente dependiendo de la memoria. En todo caso, podías haber probado más configuraciones diferentes y sobre todo sistemas operativos diferenets, los hipervisores no son tan diferentes.

**Comment by PSanchezR** [comment]
Cierto me habría sido mas facil realizarlo con kvm o azure pero comencé a realizar la práctica con virtualbox y probando las configuraciones del procesador me fallaba la aplicación y no encontraba el error por eso decidí probar con hipervisores diferentes cambiando la memoria ram únicamente. El diagrama de tarta es la aplicación que utiliza de google chart, no representa ninguna información sobre las pruebas realizadas con apache benchmark.
Supongo que la variación con respecto a la ram se debe a que con un solo GB de ram el sistema operativo funcionaba demasiado lento ya que tiene que cargar el entorno gráfico y por ello iba algo más rapido al utilizar 2 GB

**Comment by JJ** [comment]
La cuestión no es que uses Google Chart, sino que los diagramas de tarta se usan exclusivamente para porcentajes, no para presentar dos cantidades frente a frente.

**Comment by PSanchezR** [comment]
No JJ lo que quiero decir es que el gráfico es lo que hace mi aplicación, la aplicación que he montado en el servidor es una página web que utiliza google chart para hacer gráficos, el gráfico no es ninguna representación visual de los datos obtenidos por AB.

**Comment by JJ** [comment]
Ah, OK, perdón...

**Comment by PSanchezR** [comment]
No te preocupes si el fallo a sido mio por no poner un gráfico de los resultados entre otros muchos errores

**Comment by JJ** [comment]
Tampoco tantos, hombre. No te fustigues.

**Comment by PSanchezR** [comment]
jajajajja gracias por el consuelo.
