### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by franciscomanuel** [IV-GII/GII-2013#108]
Enlace a la fuente de la práctica 3:https://github.com/franciscomanuel/Practica3
Enlace a la documentación de la práctica 3:https://github.com/franciscomanuel/Practica3/blob/master/README.md

**Comment by JJ** [comment]
Para variables categóricas como esta no se usan líneas, sino barras o puntos. Aparte, el eje y debe empezar en 0, si no se exageran las diferencias. No uséis excel (y menos Excel capturado) para los gráficos, hombre... Al final lo que tienes que comparar es el Debian con el Kubuntu, y no has puesto ningún gráfico.
