### ISSUE TITLE
¿Qué aplicaciones de tipo Software as a Service usas habitualmente?

### ISSUE THREAD

**Issue by JJ** [IV-GII/GII-2013#11]

**Comment by rafacruiz** [comment]
Las aplicaciones Sotware as a Service que más uso a diario son dropbox y gmail.

**Comment by JJ** [comment]
@rafacruiz de hecho, Dropbox es "Infraestructure as a Service". Provee un servicio de almacenamiento, con alguna cosa más...

**Comment by rafaelgonz** [comment]
En mi opinión el SaaS más importante y que más servicios ofrece es google en general, con su correo, chat, nube online (google drive), posibilidad de hacer webs prefabricadas, google docs...

**Comment by antonioguirola** [comment]
Las aplicacines SaaS que más utilizo son:
- La interfaz web de GMail.
- El reproductor de música Grooveshark
- El editor de textos de Code Academy
- Las aplicaciones de ofimática de Google Docs

**Comment by SergioMGamarra** [comment]
Los SaaS que utilizo habitualmente son: Google Drive, Google Maps, Gmail o Google Calendar, y otros SaaS de gestión de proyectos como GitHub, TeamBox o RedMine.

**Comment by JoSeF267** [comment]
Los SaaS que utilizo mas a diario son : Gmail , Google Docs ,Github bastante

**Comment by franvalverde** [comment]
Las SaaS que mas uso: Google Docs, Gmail y ultimamente GitHub

**Comment by pedroag** [comment]
Los Saas más utilizados en este momento son: Gmail y GitHub.

**Comment by JJ** [comment]
Google Drive, de por sí, es IaaS. Las aplicaciones sobre google Drive sí
son SaaS

2013/10/11 Sergio Muñoz Gamarra notifications@github.com

> Los SaaS que utilizo habitualmente son: Google Drive, Google Maps, Gmail o
> Google Calendar, y otros SaaS de gestión de proyectos como GitHub, TeamBox
> o RedMine.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/11#issuecomment-26121501
> .

## 

JJ

**Comment by JJ** [comment]
@josef267 Dropbox no lo es. Es más bien IaaS: ofrece almacenamiento.

2013/10/11 JoSeF267 notifications@github.com

> Los SaaS que utilizo mas a diario son : Gmail ,Dropbox , Google Docs
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/11#issuecomment-26123476
> .

## 

JJ

**Comment by josemlp91** [comment]
Otros SaaS que utilizo  son Prezi y Office365

**Comment by josecolella** [comment]
Los SaaS que uso más habiltualmente son las redes sociales como Facebook y Twitter, y además los servicios de correo como Yahoo, Gmail. Otros que no uso pero son usados por otros son Microsoft Office 365 y Turbo Tax Online

**Comment by franciscomanuel** [comment]
Las SaaS que uso habitualmente son:  Google Docs y Gmail

**Comment by PSanchezR** [comment]
Los Saas que mas utilizo son los proporcionados por google como Gmail, las aplicaciones montadas sobre Google drive, etc. También la plataforma de reproducción de audio Spotify y la plataforma de reproducción de vídeo Youtube.

**Comment by torresj** [comment]
Las SaaS que mas uso son gmail y Facebook. Aunque uso otras de forma menos habitual como puede ser spotify o twiter. Github es otro SaaS que desde hace poco uso con mucha frecuencia

**Comment by elmendacorp** [comment]
Dropbox, gmail, practicamente casi todo esta como saas.

**Comment by germaaan** [comment]
El SaaS que más uso sin duda es Gmail, ya que por motivos cotidianos reviso el correo varias veces a diario, también uso mucho Facebook para comunicarme con otras personas, Twitter para comentar diversas cosas a diario, Youtube para ver videos y Disqus para realizar comentarios en las páginas de diversos sitios webs.

**Comment by R-R-R-R-1** [comment]
Sin duda reitero lo dicho por mis compañeros, pues yo también uso de forma muy continuada Gmail, así como también otros servicios de Google como son Google Docs o Calendar. 

Otros que también uso son Dropbox (para almacenamiento y compartición en la nube), Grooveshark (como reproductor on-line) o todos los relacionados con las redes sociales (Facebook, Twitter, etc.)

**Comment by jcastilloprez** [comment]
Las aplicaciones Software as a Service que utilizo habitualmente son: 
- Gmail y Outlook como servicios de correo. 
- Grooveshark, Spotify y Youtube como reproductores de música.
- Facebook como redes sociales.

**Comment by STiago** [comment]
Las SaaS que más uso son Gmail, Twitter  y ultimamente GitHub.

**Comment by oskyar** [comment]
Las aplicaciones que uso más frecuentemente son:
- Gmail y Outlook,  como servicios de correo.
- Facebook, Twitter y Netwie como redes sociales y blog.
- Spotify como servicio de reproducción de música.
- Battlefield 3, Candy Crush Saga como juegos (Lo mismo que son...)
- Antes SVN pero ahora mucho más GitHub.

Incluyo Battlefield 3 como SaaS porque para acceder a él tiene que ser mediante un SaaS llamado [Battle Log](http://battlelog.battlefield.com/bf3/es/gate/) (Aunque tengas que instalarte el juego).

**Comment by fllodrab** [comment]
Las aplicaciones SaaS que más uso son:
-Facebook, como método de comunicación.
-Google Hangouts, como método de comunicación y monitorización remota.
-Twitter, como vía de información y también de socialización.
-Youtube, como reproductor de música.
-QuakeLive, como entretenimiento (aunque no lo uso tanto)
-Y últimamente GitHub.

**Comment by jpm88** [comment]
Las aplicaciones SaaS que más uso son:
- Twitter y Facebook para comunicación.
- GitHub para la asignatura
- Gmail y Outlook como servicio de correo.
- Prezi para presentaciones online.
- Steam y Origin para entretenimiento.
- Youtube como reproductor de música/video

**Comment by rogegg** [comment]
Outlook, Facebook y Youtube son las aplicaciones SaaS que habitualmente utilizo. En menos uso el reproductor web de Spotify y, como han dicho los compañeros, desde hace poco Github para la asignatura.

**Comment by anaprados** [comment]
A parte de las ya mencionadas, me atrevo a decir que Whatsapp es una aplicación SaaS que uso a diario

**Comment by JJ** [comment]
No hay aplicaciones de escritorio que sirvan como mensajería; una aplicació
de mensajería no se entiende si no es en la red. SaaS es sólo cuando se
trata de una aplicación de escritorio que se haya trasladado a la red, por
lo tanto WhatsApp, según ninguna definición, sería un SaaS

**Comment by juandavarju** [comment]
Las aplicaciones SaaS que más utilizo son: Youtube, Twitter, Facebook, Gmail y Duolingo (la cual esta bien para "chapurrear" idomas, os la recomiendo).

**Comment by JaviRubio** [comment]
Los servicios SaaS que mas utilizo son los de google, especialmente gmail y google music. Redes sociales como facebook y twitter,ocasialmente G+. Ademas también he usado durante mucho tiempo el SWAD, y ahora aqui en Alemania estoy usando mucho una plataforma llamada Stine que principalmente me permite gestionar la matriculacion de mis asignaturas y seguirlas,proporcionarme automaticamente mi horario y funciones de mensajeria interna.

**Comment by JJ** [comment]
@juandavarju Salvo Duolingo, que no sé lo que es, y GMail, el resto no son SaaS. Cualquier aplicación que se ejecute en Internet no es un SaaS. @JaviRubio igual. ¿Stine es libre?

**Comment by JaviRubio** [comment]
@JJ Pues por lo que parece es una solución propietaria que empezaron a desarrollar sobre 2005, aunque la licencia no la he encontrado. Moverse en las paginas en alemán es complicadete xD

Y sobre que el resto no son SaaS, la verdad es que parece un tema que se presta a debate

En el caso de dropbox dicen que es SaaS en multitud de sitios

Por ejemplo aqui: http://www.genbetadev.com/programacion-en-la-nube/entendiendo-la-nube-el-significado-de-saas-paas-y-iaas

En el articulo de la wikipedia tambien lo citan como ejemplo

http://www.genbetadev.com/programacion-en-la-nube/entendiendo-la-nube-el-significado-de-saas-paas-y-iaas

Aqui tambien apoyan que Dropbox es un SaaS

http://www.skytap.com/blog/demystifying-saas-paas-and-iaas

En este enlace ponen a facebook como ejemplo de SaaS

http://www.wolfframeworks.com/cloudcomputing.asp

De hecho leyendo las definiciones del enlace de la wikipedia puesto en los apuntes, lo que yo entiendo por IaaS son recursos de nivel mas bajo. Por ejemplo si dropbox me permitiera montar mi espacio de almacenamiento como unidad de red entonces si, pero como aplicación que sincroniza contenidos yo creo que encaja mejor en la definición de SaaS,(sacada de este articulo: http://en.wikipedia.org/wiki/Software_as_a_service ) donde dice que SaaS es un modelo de distribución de software basado en almacenar el software junto a los datos en la nube y a los que normalmente se accede con un terminal tonto(thin client) o un navegador web. En este caso en vez de un navegador usamos una aplicación especifica para conectar con la nube, pero también podemos acceder desde la pagina web y realizar todas las operaciones que queramos, aunque en general sea mas incomodo.

Con las redes sociales pasa lo mismo, si seguimos esa definición al pie de la letra,encajan bastante bien, asi que yo pienso que nuestros ejemplos si se podrían considerar validos.

**Comment by JJ** [comment]
@javirubio según la definición de la wikipedia
http://en.wikipedia.org/wiki/Software_as_a_service SaaS son aplicaciones y
datos en un servidor a los que se accede mediante un "cliente delgado",
generalmente el navegador. Dropbox usa un servicio instalado. Además, el
modelo de pago es por tiempo o uso de recursos; Dropbox se paga por espacio
de almacenamiento. De hecho, en el mismo artículo de la wikipedia aparece
como SaaS, pero no todo lo que aparece en Internet es cierto :-) y si
llamamos SaaS a cualquier aplicación a la que se acceda por Internet, con
navegador o no, nos quedamos con una definición inútil que incluiría desde
un formulario hasta un servidor FTP. Por eso prefiero ser un poco
restrictivo en la definición, incluyendo sólo y exclusivamente aplicaciones
de escritorio a las que se accede desde un cliente web, como Google Apps o
GMail.

**Comment by JaviRubio** [comment]
@JJ Estoy deacuerdo en que no todo lo que sale en internet es cierto, pero si mucha gente tiene opiniones diferentes creo que se puede considerar que no hay consenso al respecto o se presta a debate.

En cuanto a considerar solo las aplicaciones de escritorio a la que se accede desde un cliente web yo creo que es ser excesivamente restrictivo, ya que elimina casi todas las aplicaciones existentes, cuando tomando la definición de por si encajan perfectamente. De ahi que los compañeros insistan una y otra vez en las mismas aplicaciones. En cuanto a lo de ftp, yo creo que un cliente web ftp si podria considerarse SaaS, que no digo que sea una verdad absoluta, solo mi opinión, de hecho yo creo que realmente cualquier aplicación de internet enriquecida podría entrar considerarse como SaaS. Considero que el aspecto importante de la definición es el de datos+software en la nube al que se accede por thin client.

Y en cuanto a dropbox volvemos a lo mismo, yo creo que es algo mas de punto de vista que una verdad universal. Dropbox tiene características que encaja con la definición de SaaS y tiene otras que encajan menos, asi que yo considero que queda a criterio de cada uno el como clasificarlo, al menos hasta que se estandaricen una serie de criterios que tengan que cumplir una aplicación para ser considerada SaaS.

Con esto lo que pretendo decir es que los ejemplos expuestos no creo que se puedan dar por totalmente erróneos de entrada,creo que se prestan a discusión y que poseen características suficientes como para defender su inclusión dentro del grupo de los SaaS, no creo que sea algo blanco o negro, si no una cuestión de cuanto se ajusta cada ejemplo a la definición. 

Espero que esto aclare mi postura :)

**Comment by JJ** [comment]
@javirubio totalmente aclarada, pero habiendo ejemplos que encajan
perfectamente es mejor ceñirse a esos y no tomar ejemplos discutibles, o
por lo menos aclarar según qué definición a la que uno se acoge podrían ser
considerados SaaS, como tú has hecho.
Lo que quiero que quede claro con todo esto es que SaaS no es "cualquier
software que yo ejecute desde el navegador". ¿Un buscador sería un SaaS? El
aspecto de software que se ejecute en el cliente es importante; según ese
criterio lo sería Google Docs y GMail (toda la composición de textos se
hace en el cliente, así como parte de las búsquedas y alguna otra cosa)
pero ni Facebook (salvo algún jueguecito, lo que se hace en el cliente es
básicamente introducir texto y enviarlo) ni Dropbox (el cliente no es el
navegador y lo que hace es integrar con el sistema de ficheros) ni GitHub
(es un interfaz web a una aplicación de gestión de fuentes; el hecho de que
tenga clientes para Windows y Mac indica que la funcionalidad del cliente
web es muy limitada y se limita prácticamente a introducir información).
Tampoco es cuestión de democracia y de que la mayoría haya puesto Facebook
y Dropbox. Es cuestión de acogerse a una definición precisa y razonable,
pero sobre todo que aporte algo y una vez escogida esa definición demostrar
que se ha entendido el concepto poniendo ejemplos.

**Comment by JaviRubio** [comment]
@JJ entonces creo que me voy a tomar la pequeña licencia de añadir algunos ejemplo que conozco pero que no uso habitualmente que si podrían entrar en una definición mas estricta creo yo

-http://pixlr.com/ ->Editor de fotografia online, permite subir imagenes y retocarlas desde el navegador

-https://codeanywhere.net ->Editor de codigo online, con funciones como resaltado de sintaxis y indentación automatica

-http://www.pdfonlinereader.com/WebPdf2/ ->Visor de pdf online

**Comment by JJ** [comment]
@javirubio Cualquiera de ellos correspondería a la definición.

**Comment by juandavarju** [comment]
Entonces, después de leer los ultimos post.
http://ajedrez-online.es/ (para jugar al ajedrez) y https://www.filelab.com/audio-editor (que permite editar audio desde el navegador) ¿Encajarían con la definicion?

**Comment by javiercollado** [comment]
Al igual que mis compañeros, creo que Gmail es lo que más uso habitualmente. También uso muy a menudo [Wunderlist](https://www.wunderlist.com/en/). 
Creo que dentro de la definición de SaaS también entraría iWork for iCloud (Al estilo de Google Docs)

**Comment by javierGaliana** [comment]
Para correo utilizo Gmail y hotmail. Para escuchar música grooveshark. Para videojuegos Steam.

**Comment by jmanday** [comment]
Las SaaS que suelo usar son Gmail y Google Docs.
