### ISSUE TITLE
Practica 3

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#113]
Practica 3 de Infraestructura virtual
- Repositorio: https://github.com/torresj/practica-3
- Documentación: https://github.com/torresj/practica-3/blob/master/Documentación/documentacion.md

**Comment by JJ** [comment]
¿Y no podías haberte descargado mongodb directamente desde Azure?

**Comment by torresj** [comment]
Era por no tener que meter los datos a la base de datos pero sinceramente, si volviera a hacer la practica usaría mongolab y me dejaría de historias
