### ISSUE TITLE
Práctica 3

### ISSUE THREAD

**Issue by rogegg** [IV-GII/GII-2013#114]
Práctica 3 de Infraestructura Virtual

Repositorio: https://github.com/rogegg/IV_Practica3

Documentación: https://github.com/rogegg/IV_Practica3/blob/master/Doc.md

**Comment by JJ** [comment]
Las gráficas deben empezar siempre en el origen. ¿Seguro que la máquina 1 y 3 son diferentes? Dan prácticamente el mismo resultado...
Los enlaces los tienes mal.
