### ISSUE TITLE
Práctica 3

### ISSUE THREAD

**Issue by elmendacorp** [IV-GII/GII-2013#118]
Documentación: https://github.com/elmendacorp/Practica3IV/blob/master/docu.md

Repo:https://github.com/elmendacorp/Practica3IV

**Comment by JJ** [comment]
Te recuerdo que tienes la práctica 2 pendiente todavía.

**Comment by JJ** [comment]
Y en este caso tampoco corresponde a lo que se solicita en la práctica: una _comparación_ entre diferentes configuraciones virtuales y, además, de una aplicación propia.

**Comment by elmendacorp** [comment]
Cierto me faltaban los benchmarks de la maquina. Fallo mio.

**Comment by JJ** [comment]
De hecho, te falta _todo_ Como prerrequisito de entrega de la práctica
tienes que hacer un porcentaje de los ejercicios de autoevaluación
correspondientes y no has hecho ninguno (que yo haya visto)

**Comment by JJ** [comment]
Deberías haberla reabierto, en vez de cerrarla, que me pierdo. Ahora el enfoque es correcto, pero no has hecho gráficas finales, ni has sacado conclusiones.
