### ISSUE TITLE
Práctica 3

### ISSUE THREAD

**Issue by javiercollado** [IV-GII/GII-2013#126]
Aquí esta el repositorio de la práctica 3:  
[https://github.com/javiercollado/practica3](https://github.com/javiercollado/practica3)  

Aquí la documentación:  
[https://github.com/javiercollado/practica3/blob/master/README.md](https://github.com/javiercollado/practica3/blob/master/README.md)

**Comment by JJ** [comment]
Prestad atención al formateo. Tratad de usar aplicaciones lo más reales posibles. Lo del balanceo está bien porque ya lo tenéis, pero los resultados que obtengáis no os van a ser muy ùtiles.
