### ISSUE TITLE
Problema con la inserción de imágenes 

### ISSUE THREAD

**Issue by rafaelgonz** [IV-GII/GII-2013#13]
¿Alguien ha conseguido insertar imágenes en los ejercicios?

Yo he probado con una página wiki, y con un proyecto .md de mi repositorio y nada, lo he intentado poniendo el enlace de dropbox, donde están alojadas las imágenes.

Gracias

**Comment by JJ** [comment]
¿Un ejemplo?

Saludos

El 14 de octubre de 2013 16:14, Rafa notifications@github.com escribió:

> ¿Alguien ha conseguido insertar imágenes en los ejercicios?
> 
> Yo he probado con una página wiki, y con un proyecto .md de mi repositorio
> y nada, lo he intentado poniendo el enlace de dropbox, donde están alojadas
> las imágenes.
> 
> Gracias
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/13
> .

## 

JJ

**Comment by rafaelgonz** [comment]
Mis ejercicios de la clase del día 11, y uno enlace:

 ![captura 1](https://www.dropbox.com/s/0j6gzso7mbb0yis/captura1.gif)

**Comment by germaaan** [comment]
Para enlazar imágenes en las páginas del wiki la forma que he encontrado más cómoda es subir las imágenes al Dropbox como has hecho, y cuando le das a obtener el enlace público que es el que has puesto en el último comentario (https://www.dropbox.com/s/0j6gzso7mbb0yis/captura1.gif), sustituye las "www" por "dl" y le das a intro para ir a esa página, automáticamente te generará el enlace público de esa imagen, que para la imagen que has puesto me sale "https://dl.dropboxusercontent.com/s/0j6gzso7mbb0yis/captura1.gif".

Luego a la hora de editar el wiki, para que la imagen aparezca directamente en vez de el enlace pones el simbolo "!", seguido de "[NOMBRE_IMAGEN]" y la dirección de la imagen entre paréntesis. Para la imagen que has puesto podría ser:

![prueba](https://dl.dropboxusercontent.com/s/0j6gzso7mbb0yis/captura1.gif)

Así es como lo he ido haciendo yo para mis ejercicios, puedes mirarlo en el código de una de mis páginas, por ejemplo: https://github.com/germaaan/IV_GMM/wiki/Ejercicios-de-clase-del-4-de-octubre-de-2013/_edit

Si algo no funciona coméntalo a ver. Saludos.

**Comment by rafaelgonz** [comment]
Va fenomenal, muchas gracias!!!

**Comment by JJ** [comment]
Cerrando el issue pues.
