### ISSUE TITLE
Ejercicio 4 Tema 5

### ISSUE THREAD

**Issue by oskyar** [IV-GII/GII-2013#130]
En el ejercicio 4 pide lo siguiente: 
`Crear una máquina virtual Linux con 512 megas de RAM y entorno gráfico LXDE a la que se pueda acceder mediante VNC y ssh.`

¿Vale tener una VM con Debian e instalarle el entorno gráfico LXDE? o ¿me descargo una distro que tenga ese entorno gráfico por defecto?

Un saludo.

**Comment by JJ** [comment]
Sí, puede ser Debian.

**Comment by oskyar** [comment]
¡Gracias por contestar tan rápido!
