### ISSUE TITLE
Por lo que habéis visto, ¿qué preferís? ¿Ansible o Chef?

### ISSUE THREAD

**Issue by JJ** [IV-GII/GII-2013#131]
Se trata de que veáis las ventajas e inconvenientes que habéis visto a cada uno.

**Comment by franvalverde** [comment]
Chef es una herramienta de configuración. Solo es necesario entender un poco de ruby y al crearte el script .rb te automatiza toda la instalación y configuración de un paquete. Funciona a través de "recetas". 

Ansible no lo he usado pero por lo que he leído también se trata de una herramienta de configuración pero basada en python. Tiene la posibilidad de gestionar los nodos a través de SSH. 

Conforme se comprende la manera con la que trabaja chef es bastante cómodo y útil. Como se dice Más vale lo malo conocido que lo bueno por conocer. Me quedo con Chef que ya entiendo como se usa y las posibilidades que tiene. 
Creo que otro detalle a tener en cuenta es con que lenguaje de programación te sientas mas cómodo a la hora de programar (Ruby o Python) tu script.

**Comment by JJ** [comment]
Pero espérate a usar Ansible en la clase de mañana, hombre...

**Comment by franvalverde** [comment]
jajaja. ok, pero como ponía por lo que habéis visto… yo me limitado a contestar. Mañana lo vemos entonces a ver si me cambia mi forma de pensar sobre él.

**Comment by JJ** [comment]
Igual hasta te gusta más :-)

**Comment by josecolella** [comment]
Ansible es mucho más flexible al momento de usarla. No es tan rigido con los directorios como Chef. Además tienes la flexibilidad de que puedes ejecutar ansible desde afuera mientras que chef tiene que tener las recetas adentro del servidor. Chef es más rápido que Ansible pero Ansible es más flexible con su fácil gestión de multiples máquinas. El sintaxis de Chef es un poco más claro que el que usa Ansible. Es dificíl escoger entre los dos ya que proporcionan un alternativa bastante elegante sobre uso de script del gestionamiento de máquinas servidoras.

Si tuviera que escoger escogería ansible ya que no tiene que crear los ficheros de automatización dentro de la máquina servidor para poder usarla, aunque en ambos casos tenemos que instalar los paquetes de dependencias correspondientes a los sistemas de automatización

**Comment by rafaelgonz** [comment]
Pos a mi me gusta bastante más ansible, y los ejercicios que hay de ansible por ahora, se hacen muy bien, y no son difíciles.

Y mirad que bonito jeje https://www.dropbox.com/s/93s2aiomftp6i11/pantallazo6.png

**Comment by germaaan** [comment]
Por un lado tenemos que Ansible es más cómodo de usar por la simple razón de que realizar un playbook y ejecutarlo directamente se hace menos engorroso que tener que hacer crear toda la estructura de directorios y archivos que necesitan las recetas de Chef. 

Chef quizás en su sintaxis y opciones sea más intuitivo para algunas mismas tareas respecto a Ansible, por ejemplo, a la hora de desinstalar un paquete:
- Chef:

```
package "nginx" do
  action :remove
end
```
- Ansible:

```
---
- hosts: all
  sudo: yes
  tasks:
    - name: Instalar Nginx
      apt: name=nginx state=absent
```

Pero en otros casos se hace más molesto, como mostrar un simple "Hola mundo" por pantalla (algo que podría ser también cualquier otro comando con una mayor utilidad):
- Chef:

```
execute "Muestra mensaje" do
  command "echo 'Hola mundo'"
  action :run
end
```
- Ansible:

```
---
- hosts: all
  sudo: yes
  tasks:
    - name: Muestra mensaje
      command: echo 'Hola mundo'
```

No sé si quizás en unos ambientes determinados uno puede ser más útil que otro, pero yo por lo menos me he encontrado mas cómodo usando Ansible (cuando no me daba errores, claro está).

**Comment by torresj** [comment]
Después de usar ambos creo que chef tiene una sintaxis mas cómoda y el hecho de que se use ruby es un punto a favor. Pero tener que crear la estructura de carpetas y archivos me parece una clara desventaja. En ese sentido ansible es mucho mas cómodo y su sintaxis tampoco es mucho mas complicada que la de chef. Además otra gran diferencia es que chef se ejecuta en la propia maquina donde se instalan las recetas mientras que ansible te permite    configurar las maquinas de forma remota a través de ssh y sin que en la maquina destino sea necesario tener nada instalado. Ansible también permite configurar varias maquinas a la vez creando un grupo.

En definitiva, a la pregunta de este issue respondería que depende. Si vas a configurar una sola maquina yo lo haría con chef. Si vas a configurar muchas maquinas a las cuales tienes acceso a través de la red, usaría ansible. De todas formas no siempre vas a tener un equipo anfitrión para configurar maquinas, en cuyo caso sería mejor tener las recetas de chef en github, por ejemplo, y solo clonar y lanzar chef.

Si tengo que mojarme con alguna a la fuerza, prefiero chef pese a las pegas antes descritas.

**Comment by jcastilloprez** [comment]
Si tuviera que quedarme con uno de los dos me quedo con Ansible, ya que este me ha parecido más fácil a la hora de utilizar que Chef. Sobre todo a la hora de los directorios que en Chef tuve problemas a la hora de crear tanta cadena de directorios que la verdad llegue a perderme un poco entre ellos.

**Comment by josemlp91** [comment]
Depende del uso, chef para realizar la configuración de una máquina aislada esta bastante bien, para hacer un despliegue grande donde se integren muchas máquinas, desde luego ansible es la mejor opción.

**Comment by oskyar** [comment]
En vista de mi experiencia, y a los errores de ambos gestores de configuraciones, no me decantaría por ninguno en concreto, todo dependería  del entorno en el que estuviera. Por ejemplo como han comentado anteriormente mis compañeros, si hay multitud de máquinas y queremos tener la misma configuración en todos (imaginemos un cíber) veo mucho más fácil y práctico usar los playbooks de ansible, que aunque es algo lento para cada tarea por simple que sea, si que te ahorrará tiempo en la configuración de las máquinas.
Respecto a chef, todavía seguiría perdido si no es por @torresj que me echó una mano en entender la estructura de carpetas que tenía que crear ( aunque tampoco leí mucho la verdad...). Si bien es cierto que ruby es un lenguaje bastante sencillo y en el que es muy fácil instalar programas que estén en los repositorios, no sé hasta qué punto dificultaría añadir un repositorio o descargar archivos desde servidores externos para proceder a la descompresión e instalación "manualmente".

Así que... creo que preferiría ansible como gestor de configuraciones, aunque también es verdad que he profundizado muy poco con chef.

**Comment by R-R-R-R-1** [comment]
Pues verdaderamente yo prefiero ansible, ya que, como dice el issues, basándome en lo que he visto y de como me ha ido, me ha sido más fácil manejar y entender ansible, pues con chef me he liado un poco. Supongo que sin buceara un poco más descubriría que cada uno tiene sus ventajas según el uso que deseemos darle. Pero vamos para gustos colores.

**Comment by jpm88** [comment]
Yo también opino que ansible es mejor, por lo que lo he utilizado es bastante más intuitivo y sencillo de utilizar que chef.

**Comment by jmanday** [comment]
Yo me quedo con ansible, me ha resultado más fácil su aprendizaje y posterior uso. Su configuración es mas sencilla que la de chef (por lo menos para mi).

**Comment by JoSeF267** [comment]
Sin duda alguna me quedo con ansible , cuando he utilizado chef me ha dado algún que otro problema y es un poco mas enrevesado, sin embargo, ansible es fácil , intuitivo y algún fallo que otro ha sido fácil y rápido solucionarlo.

**Comment by fllodrab** [comment]
Si no fuera por que no me funciona diría que me quedo con ansible pero no se si es por que he usado mac os x, pero ansible no me funciona bien. Asique me quedo con chef, aunque por lo que he visto ansible es mucho más fácil de configurar y si todo hubiera funcionado bien me quedaría con éste.

**Comment by JJ** [comment]
A lo mejor lo que no funciona es OS X :-)

**Comment by franvalverde** [comment]
Como ya comente antes de ver ansible, chef me parece una buena herramienta y me parece que la gente le da un poco de lado porque quizás requiera mas tiempo en entender como trabaja. 
Lo bueno que tiene ansible es que puedes tener archivos de configuración en otro lugar fuera del servidor y que quizás su sintaxis sea mas fácil de comprender que chef.

**Comment by Jmf91** [comment]
Por mi experiencia usando sendas herramientas, me quedo con Ansible. Es mucho más facil a la hora de configurar y no requiere la creación de "recetas", como ocurre con chef.

**Comment by JaviRubio** [comment]
Pues para dar la nota discordante, yo me quedo con chef, que me ha dado menos quebraderos de cabeza que Ansible, que me ha resultado bastante tikismikis con el formato de los playbooks, en cuanto a tabuladores y espacios. Con chef no he tenido ningun problema ni de configuración ni de funcionamiento.

**Comment by antonioguirola** [comment]
Yo he encontrado más sencillo de utilizar ansible, puede que sea porque le he dedicado más tiempo que a chef. El hecho de poder aprovisionar las máquinas remotamente y la facilidad con la que añadir/eliminar hosts me han convencido, además la documentación es muy completa y es muy sencillo encontrar lo que buscas, la de chef quizá intimide de primeras.

**Comment by elmendacorp** [comment]
Pues yo por lo que he visto a nivel inicial ansible parece mucho mas sencillo que chef, aunque lo que he leído y visto en un par de vídeos de gente que gestiona sistemas es que se suele usar mucho mas chef a nivel de empresa, según dicen es por el sistema que sigue a la hora de obtener los paquetes para el propio sistema. Por sencillez de uso ansible, con formación para el futuro chef.

**Comment by JCristobal** [comment]
Ansible sin lugar a dudas, en mi caso Chef me ha dado muchos problemas, y aunque no me los hubiese dado, el tener que crear su estructura lo encuentro muy pesado. Además Ansible me a parecido muy organizado, a la hora de mostrar fallos y en la gestión de las máquinas.

**Comment by ghost** [comment]
Particularmente prefiero Chef. Me ha gustado la organización más modular con metadata.rb y  default.rb, y además Ansible me ha dado algunos problemas. Chef quizás sea más tedioso pero ha funcionado desde el principio y he encontrado más documentación.

**Comment by josecsh** [comment]
Particualmente prefiero Ansible. Me resulta menos complicado de usar. Aun que como bien han dicho por aquí, Chef se usa más en el terreno empresarial y está mucho mas documentado por internet.

**Comment by toranzo** [comment]
Opino que Chef es mejor opción que Ansible. Da muchísimos menos problemas que Ansible, por lo menos en cuanto respecta a mi. Es cierto que se hace realmente pesado crear su estructura, pero sigo opinando que da menos problemas.

**Comment by enpi** [comment]
Es cierto que la estructura que ofrece Chef es más organizada ( también requiere de más tiempo elaborar la jerarquía de directorios y ficheros ), sin embargo debido a los problemas, que en mi caso, he tenido en cuanto a su instalación : problemas de compatibilidad con versiones de Ruby, incluso problemas con algunos sistemas operativos..., prefiero Ansible, que me resultó fácil de instalar y poder realizar todo con el playbook es, para estos ejercicios, bastante ventajoso.
En cuanto a la documentación disponible no he tenido problemas para solucionar dudas de Ansible.
