### ISSUE TITLE
Ultima Practica

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#133]
¿Mañana vamos a empezar a hacer algo?¿hay que llevar el portatil?¿o solo se van a presentar los trabajos?

**Comment by JJ** [comment]
Hola,

El 22 de enero de 2014, 18:58, Jaime notifications@github.com escribió:

> ¿Mañana vamos a empezar a hacer algo?¿hay que llevar el portatil?¿o solo
> se van a presentar los trabajos?

Sólo presentarse los trabajos y empezar a repartir los grupos; si da
tiempo, se verá qué puede hacer falta y el viernes en clase empezamos a
provisonar lo que haga falta.
