### ISSUE TITLE
Entrega última práctica

### ISSUE THREAD

**Issue by germaaan** [IV-GII/GII-2013#135]
¿De la última práctica hay que "formalizar" una entrega de la misma para una fecha en concreto?

**Comment by JJ** [comment]
Sí, para el día 10 de febrero, digamos.

2014-01-26 German Martinez notifications@github.com

> ¿De la última práctica hay que "formalizar" una entrega de la misma para
> una fecha en concreto?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/135
> .

## 

JJ

**Comment by germaaan** [comment]
Ok ok, así habrá tiempo de presentar algo presentable.
