### ISSUE TITLE
Duda sobre la Práctica Final

### ISSUE THREAD

**Issue by jpm88** [IV-GII/GII-2013#136]
Hola JJ, ¿a los que no hemos hecho el proyecto de coworking hay alguna opción de poder entregar algo y recuperar (al menos) una parte de los dos puntos?

Saludos.

**Comment by JJ** [comment]
Simplemente haced la práctica siguiendo el guión, buscando una aplicación
lo más real posible.

**Comment by jpm88** [comment]
Ok, duda aclarada, gracias.
