### ISSUE TITLE
Práctica 4: Cafeteros Cocorocó

### ISSUE THREAD

**Issue by josecolella** [IV-GII/GII-2013#138]
Profesor,
- La documentación de la práctica se puede encontrar en el siguiente enlace.
  https://github.com/IV-GII/Cafeteros/blob/master/README.md
- El repositorio se encuentra en el siguiente enlace.
  https://github.com/IV-GII/Cafeteros
- La url del sitio es la siguiente: 
  http://cafeteros-cocoroco.rhcloud.com/
- La presentación se puede encontrar en la siguiente url: 
  http://www.slideshare.net/JoseMiguelColella/prctica-4-ivdai-presentacion-cafeteros-cocoroc

Finalmente los miembros del grupo:
@antonioguirola, @SergioMGamarra, @javiercollado, @elmendacorp, y @josecolella

**Comment by JJ** [comment]
Habéis hecho un buen trabajo.
