### ISSUE TITLE
Duda ultimo ejercicio tema 6.

### ISSUE THREAD

**Issue by josemlp91** [IV-GII/GII-2013#139]
El último ejercicio del tema 6, "Configurar tu máquina virtual usando vagrant con el provisionador ansible", ¿cual es la idea?, Que utilicemos  directivas dentro del Vagrantfile o que realicemos el aprovisionamiento con Ansible, como si se tratase de cualquier otra máquina virtual.

**Comment by josecolella** [comment]
Dentro del Vagrantfile puedes especificar que quieres usar ansible como sistema de provisionamiento. Aqui esta como hacerlo http://docs.vagrantup.com/v2/provisioning/ansible.html

**Comment by josecolella** [comment]
En el vagrantfile va a estar presente la direccion de tu playbook

**Comment by josemlp91** [comment]
Gracias tocayo, lo repasare entonces.
