### ISSUE TITLE
Práctica Final

### ISSUE THREAD

**Issue by germaaan** [IV-GII/GII-2013#140]
Dirección del fuente de la práctica:
https://github.com/IV-GII/Django_Traduccion

Enlace a la documentación de la práctica:
https://github.com/IV-GII/Django_Traduccion/blob/master/README.md

Enlace a la aplicación funcionando:
http://asdfteam.cloudapp.net/

Desarrolladores:
José Manuel Castillo Pérez (@jcastilloprez)
Iñaki Fernández Janssens de Varebeke (@FdezI)
Manuel Jesús García Manday (@jmanday)
Germán Martínez Maldonado (@germaaan)
Elisabet Romero Vaquero (@Elirova)
Javier Rubio Giménez (@JaviRubio)
Pablo Sánchez Robles (@PSanchezR)
María Victoria Santiago Alcalá (@STiago)
Juan David Vargas Jiménez (@juandavarju)

**Comment by JJ** [comment]
Muy buena la parte IV, aunque está claro que no ha sido entre todos...

**Comment by FdezI** [comment]
Hay muchas cosas, que aunque parezcan hechas entre uno solo, podría sorprenderle quién ha participado y quién no. Uno de los objetivos principales de la práctica era el "coworking" pero parece ser que no se esperaba para nada que se trabajara de forma cooperativa. Estando todos en una sala y en un mismo entorno de trabajo agiliza y mejora el resultado del trabajo realizado. Parte de esta agilidad se debe a la NO necesidad de tener que estar usando internet para comunicarse y el hecho de poder comentar las cosas en persona, pudiendo resolver las dudas rápidamente y ayudando a otro a realizar algo que por sí solo tardaría más o realizaría de forma menos óptima.
Sin embargo, por todas las críticas obtenidas debería deducir que lo que se esperaba era que trabajáramos en un entorno de "coworking" sin aprovecharnos del entorno, sino usando herramientas de trabajo remoto. Un auténtico despilfarro de tiempo y de recursos. En un principio la idea era muy buena y así ha sido la experiencia, por sus críticas, sin embargo, podría decirse que el objetivo de la práctica y la idea no estaban del todo claras.
Cada recurso, herramienta, entorno de trabajo ha de usarse en determinado tiempo y lugar. No por conocer una herramienta ni ser ésta la mejor del mundo para cierto trabajo lo es para otro, no porque herramientas de trabajo remoto sean "la hostia", es la mejor opción en un entorno de "coworking".

Tanto es así que su respuesta no me parece para nada educada ni justa con los compañeros a los que pretende subestimar. Ha sido un trabajo en grupo, algunos han "commiteado" más, otros han apoyado y ayudado más a los que necesitaban ayuda para realizar posteriormente un "commit" con algo hecho (este algo es, por lo tanto, resultado de más personas, no únicamente del que ha realizado el commit) y, sobre todo, no todos han hecho la misma parte por lo que, obviamente, esa parte, "no ha sido entre todos...." pero tampoco obra de uno solo.

**Comment by JJ** [comment]
Cuando digo _está claro_ es que [está claro](https://github.com/IV-GII/Django_Traduccion/blame/master/README.md) como está muy claro, en ese mismo documento, quien no ha contribuido absolutamente nada a la documentación, al menos en la versión final. También está [muy claro](https://github.com/IV-GII/Django_Traduccion/tree/master/scripts) quién ha escrito esa parte (la parte de la asignatura, que es la que me importa y la que debo evaluar) y ha contribuido de forma única a ella. Te recuerdo que la cuarta práctica es (la cuarta práctica de la asignatura de Infraestructura Virtual)[http://jj.github.io/IV/documentos/practicas/4.Aplicaciones] y que, evidentemente, lo que se evalúa es lo que se ha hecho y lo que está en el repositorio y no la idea brillante que hayas podido tener (o no) no estando yo presente (cosa que, por otro lado, es prácticamente imposible de evaluar objetivamente). Así mismo, y teniendo en cuenta los dos enlaces que te he mostrado anteriormente, lo correcto habría sido suspender en esa práctica a una persona que por no aportar a la documentación del proyecto, no ha aportado ni la línea que contiene su propio nombre, pero teniendo en cuenta el trabajo conjunto (donde se consideran todos esos factores que mencionas, al menos los efectos de los mismos) las notas en general del proyecto creo que no han sido precisamente bajas. Si hay una falta de educación, hacia el profesor y los compañeros, es convertir una crítica fundada (como enlazo anteriormente) en una falta de respeto y, sobre todo, sin siquiera leerse la práctica ni, aparentemente, haber visto la nota obtenida hablar de "herramientas no necesarias" cuando eran el tema de una asignatura, y evidentemente el de la práctica, que es lo que yo evalúo.

**Comment by FdezI** [comment]
He visto mi nota antes de enviar ningún mensaje, he visto los resultados, estadísticas y conozco las herramientas de github para controlar el trabajo realizado. Aún así, sigo defendiendo que no es un sistema de medida único adecuado, quizás más certero que otros muchos, pero, incluso siendo la mejor forma de evaluación posible, veo sobrante los comentarios favoritistas y con segundas constantes. No hay nada peor que trabajar y currarte algo para que luego venga un "superior" a decirte que no has hecho nada. Si alguien pone tu nombre en la documentación, no lo vas a cambiar simplemente para tener el "commit" ahí metido. Si las tareas se asignan de cierta forma no vas a meterte en medio simplemente para decir: "eh, eh, que yo esto también sé hacerlo" o "no, no, la nota la quiero yo". Simplemente, cada uno ha llevado a cabo labores distintas y muchas de ellas no plasmables en "commits".

Por ello en ningún momento he hecho referencia a las notas obtenidas en esta práctica sino a la forma de comentar las cosas ya que, por lo menos en esta ocasión, las notas las he visto correctas.

**Comment by JJ** [comment]
Si las notas son correctas y te he probado que lo que digo en el comentario es absolutamente cierto, ¿por qué diablos estamos perdiendo el tiempo?
