### ISSUE TITLE
Práctica Final: Ingenia

### ISSUE THREAD

**Issue by fllodrab** [IV-GII/GII-2013#141]
Documentación de la práctica:
https://github.com/IV-GII/Ingenia/blob/master/README.md

Fuentes:
https://github.com/IV-GII/Ingenia

Enlace a la aplicación:
http://ubuntu1204peq.cloudapp.net/ingenia/

---

Equipo Ingenia Tracking:
Francisco Valverde Villalba
Juan Moral Fernandez
Rafa Carrasco Ruiz
Fernando Llodra Belda

**Comment by JJ** [comment]
En los ejemplos capturados se ven conflictos de git que no habéis resuelto (donde pone HEAD). El modelo es MVC con la C de controlador, no MVT. La parte IV consiste sólo en usar Azure y ni siquiera provisionáis, por lo que es bastante deficiente.
