### ISSUE TITLE
Práctica Final

### ISSUE THREAD

**Issue by jpm88** [IV-GII/GII-2013#142]
Enlace al repositorio:

https://github.com/jpm88/Practica4-IV

Enlace a la documentación:

https://github.com/jpm88/Practica4-IV/blob/master/README.md

Enlace de la aplicación funcionado:

http://practica1-jpm88.rhcloud.com/

Desarrollador:
Juan Antonio Pérez Maldonado (@jpm88)

**Comment by JJ** [comment]
Me temo que no has entendido el concepto de provisionamiento. Por favor, vuelve a leer el último tema. No se trata simplemente de crear una máquina virtual y trabajar con ella.
