### ISSUE TITLE
Práctica Final

### ISSUE THREAD

**Issue by rafaelgonz** [IV-GII/GII-2013#143]
Entrega de la práctica final del equipo JRR Corporation, de título GranadaTS

Repositorio: https://github.com/IV-GII/GranadaTS

Documentación: https://github.com/IV-GII/GranadaTS/blob/master/README.md

Aplicación: http://granadats.cloudapp.net/

Presentación: http://www.slideshare.net/rafagonzalezjimenez/granada-tierra-soada

---

Jose López Sánchez

Rafael Gónzalez Jiménez

Raúl Sánchez Fuentes

**Comment by JJ** [comment]
En general, bien, aunque creo que habéis liado el aprovisionamiento más de la cuenta.
