### ISSUE TITLE
Práctica Final

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#144]
Practica Final correspondiente a la aplicación SocialCookies:
- Dirección del proyecto en github
  https://github.com/IV-GII/SocialCookies
- Documentación
  https://github.com/IV-GII/SocialCookies/blob/master/Documentacion/documentacion.md
- Aplicación
  http://socialcookies.cloudapp.net/socialcookies

Los integrantes del grupo están en el final de la documentación

**Comment by JJ** [comment]
No estaría mal acreditar la autoría de la foto, aunque sea mía... Por lo demás, bien en general.
