### ISSUE TITLE
conexión lenta en máquina Debian

### ISSUE THREAD

**Issue by PSanchezR** [IV-GII/GII-2013#145]
Hola JJ estoy teniendo un problema con una máquina virtual basada Debian montada sobre el hipervisor VMware. La máquina tiene acceso a la red LAN mediante una conexión Bridge con el anfitrión (Tiene que ser Windows 8.1 :( ) y consigo hacer ping a cualquier web sin problemas y a todos los equipos de la red pero a la hora de actualizar el sistema se agota el tiempo de espera sin conseguir actualizarlo, si intento conectar mediante navegador a cualquier página también pasa lo mismo se agota el tiempo por lo que el problema es de conexión lenta. Mi pregunta es: ¿Cómo puedo configurar la conexión para que sea algo mas rápida?

**Comment by JJ** [comment]
Hola,

El 12 de febrero de 2014, 16:56, PSanchezR notifications@github.comescribió:

> Hola JJ estoy teniendo un problema con una máquina virtual basada Debian
> montada sobre el hipervisor VMware. La máquina tiene acceso a la red LAN
> mediante una conexión Bridge con el anfitrión (Tiene que ser Windows 8.1 :(
> ) y consigo hacer ping a cualquier web sin problemas y a todos los equipos
> de la red pero a la hora de actualizar el sistema se agota el tiempo de
> espera sin conseguir actualizarlo, si intento conectar mediante navegador a
> cualquier página también pasa lo mismo se agota el tiempo por lo que el
> problema es de conexión lenta. Mi pregunta es: ¿Cómo puedo configurar la
> conexión para que sea algo mas rápida?

Es difícil de saber. Prueba en la máquina invitada a hacer ping a loopback,
prueba de la máquina invitada a la anfitriona y viceversa, y así
sucesivamente, a ver dónde está el problema. Mira también un traceroute, a
ver cuál es el link de la red que es lento.. una vez que lo sepas, aplícale
alguna solución específica, pero no conozco bien VMWare y cómo depurarlo,
quizás tenga drivers específicos de virtualización, puede que puedas
cambiar el modelo emulado de tarjeta... puede que W8.1 sea una mierda... en
fin, trata de depurar primero el enlace que es lento y a partir de ahí
trata de solucionarlo.

**Comment by PSanchezR** [comment]
No he conseguido acelerar la conexión con vmware, pero he instalado virtualbox y he exportado la máquina a este hipervisor y ahora la velocidad es mucho mayor, sería algún tipo de filtro de vmware para que las máquinas no consuman mucho ancho de banda.
