### ISSUE TITLE
Práctica 1

### ISSUE THREAD

**Issue by antonioguirola** [IV-GII/GII-2013#17]
Entrega de la práctica 1:
- https://github.com/antonioguirola/periodico

La aplicación se puede probar en:
- http://appdeprueba-antonioguirola.rhcloud.com

La aplicación no muestra los banners publicitarios en el index ni en las secciones generales y no se por qué, ya que la misma aplicación en mi servidor local sí las muestra correctamente.

**Comment by JJ** [comment]
No has usado ninguna licencia ni documentado el proyecto. Una mínima documentación (por qué has elegido OpenShift, por ejemplo) habría hecho falta.

**Comment by antonioguirola** [comment]
¿La puedo seguir modificando hasta el lunes?

**Comment by JJ** [comment]
S?

**Comment by antonioguirola** [comment]
Ya he añadido la licencia y extendido un poco la documentación.
