### ISSUE TITLE
Ejercicio 7

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#2]
¿El ejercicio 7 hay que reflejar que se ha hecho haciendo una pagina en el wiki con capturas de pantalla o explicando lo que se ha hecho?¿O simplemente con cumplir el objetivo de clase y haberlo hecho es suficiente?

**Comment by JJ** [comment]
Sí, en este caso conviene que lo hagáis. No es un ejercicio fácil y si habéis tenido que hacer algo especial convendría que lo comentárais.
