### ISSUE TITLE
Práctica1

### ISSUE THREAD

**Issue by franciscomanuel** [IV-GII/GII-2013#20]
El enlace a mi práctica se encuentra en:

https://github.com/franciscomanuel/Practica1

El enlace a mi aplicación en openShift es:

http://practica-franciscomanuel.rhcloud.com/

**Comment by JJ** [comment]
No has etiquetado ni asignado etiqueta. Tampoco has elegido una licencia para el código. la documentación es mínima, pero correcta.

**Comment by franciscomanuel** [comment]
Ya he asignado una licencia
