### ISSUE TITLE
Práctica 1

### ISSUE THREAD

**Issue by PSanchezR** [IV-GII/GII-2013#26]
Repositorio de la práctica:
https://github.com/PSanchezR/pr-cticas
En dicho repositorio esta incluido el código y la documentación de la misma.

La práctica funcionando bajo PAAS openshift:
http://practica1-practicasiv.rhcloud.com/

**Comment by JJ** [comment]
La documentación tampoco es demasiado amplia y tienes un error en la codificación de caracteres (último pantallazo)

**Comment by PSanchezR** [comment]
Solucionado el problema en el último pantallazo, cambio de README a README.md, añadido el fichero LICENSE.md, y eliminados los echos en el código para mostrar el HTML
