### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by josemlp91** [IV-GII/GII-2013#29]
Hola, estos son los enlaces de  mi practica:

Aplicacion: 
http://foroivirtuales2-josemlp.rhcloud.com/

Fuentes: 
https://github.com/josemlp91/practica1/

Documentación:
https://github.com/josemlp91/practica1/wiki/Documentaci%C3%B3n-Practica-1
https://github.com/josemlp91/practica1/blob/master/docuP1.md

**Comment by JJ** [comment]
La documentación debe ir también en el proyecto como un fichero.

**Comment by josemlp91** [comment]
Arreglado, ahora la documentación también está en : https://github.com/josemlp91/practica1/blob/master/docuP1.md

**Comment by JJ** [comment]
Muy bueno y potencialmente útil.
