### ISSUE TITLE
Ejercicio 7: cgroup change of group failed

### ISSUE THREAD

**Issue by josecolella** [IV-GII/GII-2013#3]
Estoy tratando de ejecutar una order con `cgexec` dentro del grupo de control, y me da el error cgroup change of group failed. He estado buscando y no consigo como resolver este problema.

**Comment by JJ** [comment]
¿Puedes poner algún detalle más? Grupos que has definido, línea de órdenes y comando exacto.

**Comment by josecolella** [comment]
He creado tres grupos de control. Uno en el cual se limita la CPU, otro que se limita la memoria, y otra que se limitan los dos.

```
 sudo cgcreate -a $USER -g memory,cpu: primero 
```

```
   sudo cgcreate -a $USER -g memory,cpu: segundo
```

```
   sudo cgcreate -a $USER -g memory,cpu: tercero
```

El comando exacto es:

```
/usr/bin/cgexec -g 'memory,cpu:primero/' chrome
```

**Comment by JJ** [comment]
Creo que te sobran las comillas y el / al final. Los grupos de control se representan mediante directorios, pero no le hacen falta.

**Comment by josecolella** [comment]
Perfecto. Problema Resuelto
