### ISSUE TITLE
Práctica1

### ISSUE THREAD

**Issue by rogegg** [IV-GII/GII-2013#32]
## Práctica1 de Infraestructura Virtual.

Podemos ver el resultado de nuestra aplicación en:

> [http://proyecto-ivejercicio14.rhcloud.com](http://proyecto-ivejercicio14.rhcloud.com)

La documentación se encuentra en:

> [https://github.com/rogegg/practica1/blob/master/proyecto/Doc.md](https://github.com/rogegg/practica1/blob/master/proyecto/Doc.md)

Código fuente alojado en el repositorio de GitHub:

> [https://github.com/rogegg/practica1/blob/master/proyecto](https://github.com/rogegg/practica1/blob/master/proyecto)

**Comment by JJ** [comment]
Incluyes ficheros de copia de seguridad entre los del repo,
