### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by franvalverde** [IV-GII/GII-2013#34]
Aplicación -> http://periodico-franvalverdep1.rhcloud.com
Repositorio Github -> https://github.com/franvalverde/Practica1
Documentación -> https://github.com/franvalverde/Practica1/blob/master/README.md

**Comment by JJ** [comment]
Tienes que cuidar la licencia de las imágenes y los textos y añadir la cabecera de licencia a todos los ficheros.
