### ISSUE TITLE
Práctica 1

### ISSUE THREAD

**Issue by eliromeva** [IV-GII/GII-2013#39]
Documentación práctica 1: https://github.com/Elirova/GII-IV-13/wiki/Pr%C3%A1ctica-1

Aplicación: http://periodicoiv-giiiv13.rhcloud.com/

Código de la página web: https://github.com/Elirova/GII-IV-13/tree/master/PeriodicoIV

**Comment by JJ** [comment]
Documentación en fichero md, imágenes sin licencia, no has elegido licencia tampoco para la aplicación, has metido hasta ficheros lock en el repo, no está el SQL.
