### ISSUE TITLE
¿Qué aplicación puede tener la limitación o asignación de recursos en un entorno de producción?

### ISSUE THREAD

**Issue by JJ** [IV-GII/GII-2013#4]

**Comment by torresj** [comment]
En un entorno de producción puede ser interesante limitar los recursos para ver el comportamiento de la aplicación que se esta probando en determinadas condiciones. Ademas, dado que hablamos de pruebas, limitar la memoria y la CPU puede servir para prevenir comportamientos inesperados de la aplicación.

También puede ser interesante limitar los recursos en función del tipo de usuario. Por ejemplo, si un usuario está pagando mas que otro por el mismo servicio, es lógico pensar que el que paga mas debería tener mejor QoS, y por tanto mas recursos para su uso.

**Comment by josemlp91** [comment]
Creo interesante una asignación de recursos adecuada a las prestaciones con las que van a contar los usuarios finales, para así poder ver el comportamiento real de cara a los consumidores. Pues como sabemos los dispositivos que se utilizan tienen capacidades muy distintas y ya no solo se centran en los pc o laptops, ahora contamos con una gran diversidad,  sean  smartphones baja gama, tablets, smartTVs...

**Comment by JJ** [comment]
@josemlp91 Cuando hablamos de "dispositivos" nos referimos a entrada/salida y cosas por el estilo, no tablets y demás. ¿Cómo vas a cambiar con CGROUPS el tiempo que se le dedica a un tablet?

**Comment by josemlp91** [comment]
Mi idea es hacer una aproximación de los recursos de un dispositivo con recursos limitados, (como un smartphone),
un ejemplo seria que estamos desarrollando una aplicación  web responsive, destina a una empresa donde sabemos que el 70% de los empleados que la van a usar, van interactuar con ella desde sus smartphones, (con una cpu y una ram muy por debajo de las maquinas del entorno de producción), podemos tomar la decisión de limitar el entorno de producción para que se adapte mejor, y ahorrar costes al tener solo los recursos justos a lo que se nos requiere.

Otra idea que se me ocurre, es limitar los recursos para tener una reserva, para situaciones donde sabemos que se va a requerir de más recursos. Un ejemplo el servidor de "una tienda virtual" donde sabemos que en verano se usa muy poco, podemos disminuir el porcentaje de CPU y la RAM, y en la época de navidad hacer una asignacion de recursos máxima.

**Comment by pedroag** [comment]
Básicamente se utilizaría para no "malgastar" recursos en aplicaciones que no requieren de tanta importancia un entorno de de producción determinado.

**Comment by antonioguirola** [comment]
A la hora de asignar recursos a un determinado programa en lo que hay que fijarse es en la cantidad de recursos compartidos que necesita, como capacidad de cómputo o espacio en memoria principal, de manera que se garantice un uso equitativo de los recursos por parte de todos los usuarios del entorno de producción.

Como ejemplo podemos suponer un sistema que realice simulaciones sobre la evolución de la meteorología en una determinada zona, dado el gran esfuerzo computacional que dicha aplicación necesita se tendría que establecer una limitación en el uso de la CPU para que el mayor número posibles de usuarios puedan usarlo.

**Comment by SergioMGamarra** [comment]
La limitación o asignación de recursos en un entorno de desarrollo se puede aprovechar para optimizar al máximo los recursos de dicho entorno. Podemos asignar  recursos de forma que todas las aplicaciones dentro del entorno de producción tengan a su disposición los recursos que le son necesarios, de forma que ninguna aplicación tenga falta de recursos en ningún caso ni ninguna aplicación malgaste cierto porcentaje de algún recurso.

**Comment by josecolella** [comment]
Una posible aplicación de limitación o asignación de recursos es el gestionamiento de multiples clientes como lo que hacen las empresas de hosting o las empresas que suelen rentar servicios a usuarios. Lo que suelen hacer es limitar los recursos de procesamiento, memoria, entrada/salida, y/o ancho de bancha disponible al usuario. Esto es útil para la empresa que ofrece el servicio ya que se asegura que el cliente tenga disponible los servicios que haya pagado, y facilita el gestionamiento de recursos por parte de la empresa.

**Comment by JJ** [comment]
@SergioMGamarra Hasta ahí llegamos. Se trata de que digas qué aplicación práctica en un entorno real podría tener eso.

**Comment by JoSeF267** [comment]
Pienso que la aplicación que debería de tener limitación a la hora de usar la CPU debería ser una en la cual no quisieras que afectara al entorno de producción ,es decir, si estuviéramos probando como se comportaría un programa final para un usuario y queremos ver exactamente como este explota nuestro sistema podríamos limitar la velocidad de CPU al Firefox por ejemplo ya que en verdad no seria una aplicación que queramos que afectara al desarrollo de nuestra aplicación. A la hora de limitar según servicios creo que un administrador deberá de tener mas recursos que un usuario final que pueda usar programas básicos.

**Comment by rafaelgonz** [comment]
En mi opinión, hay dos posibles aplicaciones interesantes:

1º Limitar a usuarios en cualquier aplicación web, diferenciando lo que puede hacer un usuario de pago, a uno que no es de pago, como por ejemplo cualquier "jueguecillo android" en el que los usuarios gratis tienen más limitaciones que los usuarios premium.

2º Limitar los recursos de usuarios en SO, para no malgastar recursos, como por ejemplo, un usuario, en el que sólo va a navegar por internet, se le limitan los recursos en general, CPU, memoria, gráficos...

**Comment by jcastilloprez** [comment]
Sería ver que recursos necesita en mayor necesidad tu aplicación y darle más prioridad a esos recursos y el entorno de producción que más se adecue a sus características. Después, si hay algún recurso que tu aplicación no necesite quitarle toda la prioridad para que a la hora de que otra aplicación necesite ese recurso, que tu aplicación no necesita, no se vea perjudicada en su funcionamiento. 

Un ejemplo sería una aplicación que utilizara la CPU constantemente y la memoria no la utilizara para nada, pues lo que tienes que hacer con esa aplicación es darle toda la prioridad a la CPU y quitarle la prioridad a la memoria para que si otra aplicación que solo utiliza la memoria no se vea afectada en su funcionamiento al tener que esperar que tu aplicación termine de ejecutarse para que pueda funcionar.

**Comment by franvalverde** [comment]
Un ejemplo de aplicación con limitación o asignación de recursos puede ser una plataforma para gestionar una empresa. 
Asignación de recursos: los empleados solo puedan acceder a documentos asignados para tal departamento o usar ciertas impresoras.
Limitación de recursos: algunos empleados no podrán entrar a ciertas páginas web o dispondrán de una cuota de disco reducida.

**Comment by JJ** [comment]
@jcastilloprez Eso es lo que hace la limitación de recursos, dicho con otras palabras. Os pido ejemplos reales: ¿qué aplicación real usa la CPU constantemente y la memoria para nada, por ejemplo? @franvalverde ¿cómo harías eso usando aislamiento de recursos? ¿Puedes poner un ejemplo real? En cuanto a lo de la limitación de recursos, ¡se trata de recursos del sistema! No de páginas web.

**Comment by jcastilloprez** [comment]
Una aplicación que según como esté configurada nos va a consumir más o menos recursos del sistema es el antivirus, por ejemplo el antivirus Kaspersky. Este antivirus nos analiza nuestro sistema en tiempo real mediante un análisis heurístico que se basa en algoritmos complejos y requiere un mayor uso de la CPU. Este análisis cuenta con tres niveles de protección: mínimo, medio y máximo. Si lo configuramos al mínimo necesitará menos recursos, aunque también podemos deshabilitar esta opción para consumir menos recursos. También podemos optimizar el análisis para que en vez de que analice siempre todos los archivos, solo analice los archivos que sean nuevos o hayan sido modificados. Realizando estos pasos hacemos que esta aplicación consuma menos recursos y tarde menos tiempo ejecutándose.

**Comment by JJ** [comment]
@jcastilloprez dos cosas: Kaspersky no funciona, que yo sepa, en Linux. Y segunda cosa: estamos hablando de aplicaciones reales en una empresa, no de limitación o no de recursos en un aparato de sobremesa. Por último, no se trata de que digáis que si limitamos los recursos consumirá menos recursos, que hasta ahí llegamos la mayoría: se trata de que lo planteéis en un entorno de producción.

**Comment by R-R-R-R-1** [comment]
Una posible aplicación relacionada con la limitación de recursos podría ser la gestión de un sistema de infraestructura para un banco, en donde se de prioridad a las aplicaciones encargadas de las transacciones, ya que son las operaciones más importantes y a las cuales se le deben de asignar más recursos. Mientras que las aplicaciones encargadas de dar información podrían disponer de menos recursos, limitándoles estos.
Igualmente se podrían limitar por usuarios, dándole más recursos a los usuarios encargados de las cajas, y menos a los encargados de, por ejemplo, los seguros.

**Comment by SergioMGamarra** [comment]
Un ejemplo de limitación de recursos se puede en un servidor de hosting, el cuál limita los recursos de cada cliente según el precio mensual que haya pagado. Otro ejemplo se puede dar cuando en una empresa con un solo servidor, donde hay varias plataformas subidas, por lo que las plataformas con un número mayor de usuarios se les dedicará más recursos que a otras con menor demanda.

**Comment by rogegg** [comment]
Por ejemplo en un servidor que preste servicio de conexión por escritorio remoto a un cliente, se le asignen más o menos cores y recursos del servidor dependiendo de la tarifa que elija el cliente. Obviamente a más recursos ofrecidos más caro será el servicio.

**Comment by oskyar** [comment]
Imaginemos que necesitamos un servidor y como se va a usar poco de primeras utilizamos un VPS (Virtual Private Server). Por lo tanto cogeremos uno barato que tenga pocos recursos, por lo que ya estarían limitándonos el servidor en si para nuestro servidor virtual.
Ahora bien, queremos instalarnos un sistema de Base de Datos + Servidor de aplicaciones en el servidor. De primeras se puede testear el uso de los servicios en el sistema para ver cuál necesita más recursos y de qué tipo y luego pasar a limitar esos recursos
**¿De qué manera?**
- Pues por ejemplo, si vemos que la BD utiliza muchos recursos o nosotros queremos darle prioridad para que haga las consultas y demás rápidamente, si tenemos un servidor con 4 cores, pues asignarle por ejemplo 3 cores y al servidor de aplicaciones 1 core.
- Al igual podríamos hacer con la Memoria RAM, uso del disco duro, etc.

Lo ideal sería testearlo dentro de un entorno de producción ya que tendremos la aplicación final y comprobar la fiabilidad, estabilidad, escalabilidad, etc, de la aplicación en caso de que el sistema se quede sin recursos o para hacer una configuración mucho más eficaz y eficiente para la optimización del entorno.

**Comment by jcastilloprez** [comment]
Un ejemplo de limitación de recursos se puede dar en un servidor de hosting de una empresa, el cuál limitaría los recursos de cada empleado de la empresa según el puesto y tareas que realice en la empresa.

**Comment by JJ** [comment]
@jcastilloprez una vez más, es evidente que con limitación de recursos se pueden limitar los recursos. ¿Pero qué recursos limitarías y cómo, dependiendo del puesto? Si tú fueras el jefe de Informática de Tornillos Benítez y te dijera el jefe: "límitame los recursos de los empleados". ¿Cómo lo harías?

**Comment by jcastilloprez** [comment]
Si el empleado fuera el administrador que se encarga del mantenimiento y correcto funcionamiento del servidor y nuestro servidor tiene por ejemplo 8 cores le asignaría la mitad de cores ya que es el empleado que más carga le mete al servidor y así con los demás componentes del servidor como la memoria RAM, el disco duro, etc. En caso contrario, si el empleado fuera la limpiadora que lo único que tiene que hacer es leer su cuadrante, dándole un poco de: CPU, memoria y disco duro para que pueda identificarse en el servidor y leer sus tareas tendría bastante y no tiene por qué tener los mismos recursos que el administrador. Evitando así un posible colapsamiento del sistema.

**Comment by franciscomanuel** [comment]
Las funciones de control de recursos de Oracle Solaris permiten que se comparta el ancho de banda entre las VNIC en la red virtual de un sistema. También puede utilizar funciones de control de recursos para asignar y gestionar el ancho de banda en una interfaz física sin VNIC ni máquinas virtuales.

http://docs.oracle.com/cd/E26921_01/html/E25833/gewag.html

**Comment by JJ** [comment]
@jcastilloprez estás suponiendo que en ese negocio todo el mundo se conecta en el mismo ordenador. ¿Conoces alguno en el que sea así? @franciscomanuel Muy bien. ¿Y? ¿Cómo se puede usar eso en un entorno _real_?

**Comment by germaaan** [comment]
En un empresa que tiene equipos para funcionar como terminales de punto de venta que se conectan a un servidor central para enviar y recibir datos, nos podría interesar que en esos equipos los programa relacionadas con la gestión de ventas tengan una mayor prioridad que por ejemplo otros procesos que se ejecuten en el sistema como puede ser la actualización del antivirus o los procesos en segundo plano del propio sistema operativo, por lo que separaríamos esos programas de gestión de ventas del resto a un grupo de control al que le daríamos una mayor prioridad en el procesador o incluso, en el caso de tener dos núcleos en el procesador, hacer que un núcleo se encargue solo de procesar los datos relacionados con las aplicaciones de ventas y el otro núcleo que se encargue de todo lo demás; en este mismo entorno, otro caso de utilidad de asignación de recursos sería con las aplicaciones que envían y reciben datos del servidor principal, que nos interesaría que dichas aplicaciones estuvieran en un grupo de control que nos permitiera tener una mayor prioridad de entrada/salida que por ejemplo un programa que tuviéramos instalado para obtener la previsión del tiempo en todo momento.

**Comment by fllodrab** [comment]
En cualquier empresa donde haya montada una red WAN se podría hacer una limitación de recursos controlando aquellos usuarios que estén usando mas ancho de banda y automáticamente asignarles un límite menor y así asegurar que la red WAN de la empresa no se colapse.

**Comment by JJ** [comment]
@fllodrab ¿qué tiene que ver la WAN con los recursos? ¿Cómo haces eso? ¿Qué
sistemas de autenticación y de calidad de servicio usarías?

**Comment by fllodrab** [comment]
No he dicho nada. Se me ocurre otro ejemplo: En una empresa donde hay que hacer determinadas operaciones con programas alojados en el servidor que requieren de una elevada cantidad de recursos, crearía un grupo de control donde alojar dichas aplicaciones asignandole, si por ejemplo nuestro servidor tuviera 8 cores y 64GB de RAM, 4 cores y 48 GB de RAM.  Mientras que el resto de programas que no tienen papel muy importante en la empresa y requieren de menos recursos usarían el resto de estos recursos.

**Comment by jpm88** [comment]
Un ejemplo relacionado con la limitación de recursos podría ser la gestión de un sistema de bases de datos, es posible que se necesiten más recursos en los niveles más significativos de la base de datos, ya sea relacionados con la seguridad o el almacenaje de datos privados, mientras que en los niveles menos significativos como datos poco relevantes o de menos importancia se necesiten menos recursos para gestionarlos puesto que no necesiten tanta seguridad a la hora de modificarlos.

**Comment by JJ** [comment]
@jpm88 ¿Y de qué forma, con las herramientas que se han dado en este tema, crees que se podría hacer eso? ¿Qué tienen que ver los recursos con la seguridad?

**Comment by jpm88** [comment]
@JJ Me refería en el caso de que se necesite de algún software adicional para mantener la seguridad de la base de datos, es posible que sea posible limitar los recursos según el nivel de seguridad que se desee proteger.

**Comment by JJ** [comment]
@jpm88 Lo entiendo menos todavía.

**Comment by JaviRubio** [comment]
En un sistema que requiera de una respuesta en tiempo real,como puedan ser los sistemas de control una central nuclear o de un aeropuerto, podríamos usar cgroups para limitar los recursos de los servicios no esenciales de tal manera que haya la mayor cantidad posible de recursos disponibles para los servicios criticos.

**Comment by javierGaliana** [comment]
En una empresa con diferentes departamentos, si tenemos una cpu central de alto rendimiento por ejemplo nos vendría bien limitar el uso de la cpu dándole mayor peso a los departamentos que tengan que hacer cálculos más complejos y a los que los usan por ejemplo para hacer consultas así haríamos una mejor distribución de la cpu.
Lo mismo pasaría con las operaciones de entrada/salida( archivos blkio.*) podemos limitar dichas operaciones por ejemplo si tenemos un servicio de tipo free/premium beneficiando a los que pagan por el servicio dándole mayor ratio bps.

**Comment by jmanday** [comment]
En un entorno de producción donde la red sea un uso fundamental, se le asignará o delimitará mayor o menor ancho de banda en función del empleado, si el trabajo de un empleado necesita más tráfico de datos que otros tendrá mayor ancho de banda este. Otro escenario es en una PaaS, por ejemplo en Heroku cuando te registras puedes crearte hasta 5 aplicaciones gratis, si se quiere crear mas hay que echar mano de la tarjeta de crédito, en este caso  la limitación depende de lo que puedas contratar.

**Comment by JJ** [comment]
Jesús, eso no corresponde a los servicios de virtualización sino de calidad
de servicio. No tiene nada que ver con la limitación de recursos que hemos
visto en la asignatura.

## 

JJ

**Comment by jmanday** [comment]
Corrijo...en una empresa de desarrollo, la cual esta dividida en departamentos y todos trabajando sobre el mismo servidor, al departamento de diseño gráfico se le asignará mas cpu debido a que su trabajo así lo requiere, mientras que otros departamentos, como el de implementación, tendrán limitada la cpu. Otro ejemplo que veo es el entorno de producción que tenemos en las aulas de prácticas de la escuela, en la que según sea nuestro rol (alumno, profesor, investigador, etc) tendremos asignado o limitado un recurso.

**Comment by JJ** [comment]
Jesús, tendrás que especificar un poco más. Desde hace más o menos treinta
años, cada departamento de una empresa suele tener sus propios PCs para
ellos solitos. Además, para más Inri, los de diseño tienen Macs, así que
ponte tú a virtualizarlos y además limitarles (o aumentarles) recursos...

El 22 de octubre de 2013 13:46, jesus notifications@github.com escribió:

> Corrijo...en una empresa de desarrollo, la cual esta dividida en
> departamentos y todos trabajando sobre el mismo servidor, al departamento
> de diseño gráfico se le asignará mas cpu debido a que su trabajo así lo
> requiere, mientras que otros departamentos, como el de implementación,
> tendrán limitada la cpu. Otro ejemplo que veo es el entorno de producción
> que tenemos en las aulas de prácticas de la escuela, en la que según sea
> nuestro rol (alumno, profesor, investigador, etc) tendremos asignado o
> limitado un recurso.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/4#issuecomment-26796044
> .

## 

JJ

**Comment by jmanday** [comment]
Propongo el ejemplo del sistema operativo de un servidor para ver la aplicación que tendría la asignación o limitación de recursos, vamos a distinguir entre dos tipos de peticiones, las que se realizan muy frecuentemente y hay que darles respuesta de inmediato (podemos decir que la respuesta sería en tiempo real), y las que son menos asiduas y la respuesta no es necesario darla en ese mismo instante (podemos decir que es como si estuviesen en un segundo plano). Pues bien para el primer tipo de peticiones sería necesario una mayor asignación tanto de cpu como de memoria, de camino que limitamos de los mismos recursos a las otras peticiones, las cuales en el momento en el que haya que servirle la respuesta se le asignarán mas recursos.

**Comment by JJ** [comment]
Jesús, eso es la definición de lo que hace un sistema de limitación y
gestión de recursos. ¿Un ejemplo real? ¿Qué tipo de peticiones serían las
primeras? ¿Cuáles serían las segundas? Un ejemplo real es una aplicación
con nombres y apellidos (por ejemplo, OpenOffice o MySQL) en un entorno con
nombres y apellidos (tendrá que ser un entorno en el que se use algún tipo
de servicio centralizado, un servidor departamental, servidor web, de bases
de datos, cálculo científico... un ejemplo _real_ de una situación _real_,
no hipotética.

El 22 de octubre de 2013 14:00, jesus notifications@github.com escribió:

> Propongo el ejemplo del sistema operativo de un servidor para ver la
> aplicación que tendría la asignación o limitación de recursos, vamos a
> distinguir entre dos tipos de peticiones, las que se realizan muy
> frecuentemente y hay que darles respuesta de inmediato (podemos decir que
> la respuesta sería en tiempo real), y las que son menos asiduas y la
> respuesta no es necesario darla en ese mismo instante (podemos decir que es
> como si estuviesen en un segundo plano). Pues bien para el primer tipo de
> peticiones sería necesario una mayor asignación tanto de cpu como de
> memoria, de camino que limitamos de los mismos recursos a las otras
> peticiones, las cuales en el momento en el que haya que servirle la
> respuesta se le asignarán mas recursos.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/4#issuecomment-26796794
> .

## 

JJ

**Comment by jmanday** [comment]
Como ejemplo pongo el del servicio de una aplicación bancaria, para las peticiones que sean del tipo de consultar alguna información de ayuda sobre la entidad se le limitarán los recursos tanto de cpu como de memoria (estas serían el segundo tipo de peticiones), pero para las peticiones como pueden ser un pago bancario o transferencia se le asignarían mas recursos de cpu y memoria, para que se ejecutasen en tiempo real, ya que sino podría darse el caso de con un saldo de 50 € hacer dos compras que superen esa cantidad.

**Comment by JJ** [comment]
De veras, Jesús, vas a pensar que te tengo manía. ¿Has leído el material de
la asignatura? ¿Cuál de las (o de la) aplicaciones de virtualización
mencionadas crees que van a ser capaces de distinguir entre uno y otro tipo
de peticiones? ¿Tú crees que mediante virtualización se puede comprobar si
se ha hecho una petición de más dinero del del saldo?
Si el tema bancario te interesa, estoy seguro que puedes preguntar en foros
o buscar en Google aplicaciones de virtualización en un backoffice bancario
o preguntarle a algún colega que esté en la General de becario en
Informática.

El 22 de octubre de 2013 14:23, jesus notifications@github.com escribió:

> Como ejemplo pongo el del servicio de una aplicación bancaria, para las
> peticiones que sean del tipo de consultar alguna información de ayuda sobre
> la entidad se le limitarán los recursos tanto de cpu como de memoria (estas
> serían el segundo tipo de peticiones), pero para las peticiones como pueden
> ser un pago bancario o transferencia se le asignarían mas recursos de cpu y
> memoria, para que se ejecutasen en tiempo real, ya que sino podría darse el
> caso de con un saldo de 50 € hacer dos compras que superen esa cantidad.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/4#issuecomment-26798098
> .

## 

JJ

**Comment by jmanday** [comment]
Me he vuelto a repasar el material de la asignatura y expongo otra situación, supongamos un entorno de producción donde se está desarrollando un proyecto, en ese entorno limitaremos de recursos a aplicaciones secundarias (que no son necesarias para la implementación de nuestro proyecto)  como puede ser el reproductor de música y le asignaremos mayor beneficio de recursos a aquellas aplicaciones que estén relacionadas directamente con el desarrollo del proyecto, como puede ser postgre sql si nuestro proyecto trabaja con bases de datos.

**Comment by JJ** [comment]
¿En un entorno de producción tienes un reproductor de música?

El 22 de octubre de 2013 14:51, jesus notifications@github.com escribió:

> Me he vuelto a repasar el material de la asignatura y expongo otra
> situación, supongamos un entorno de producción donde se está desarrollando
> un proyecto, en ese entorno limitaremos de recursos a aplicaciones
> secundarias (que no son necesarias para la implementación de nuestro
> proyecto) como puede ser el reproductor de música y le asignaremos mayor
> beneficio de recursos a aquellas aplicaciones que estén relacionadas
> directamente con el desarrollo del proyecto, como puede ser postgre sql si
> nuestro proyecto trabaja con bases de datos.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/4#issuecomment-26799734
> .

## 

JJ

**Comment by jmanday** [comment]
Cambiemos el ejemplo por un navegador.
