### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by javierGaliana** [IV-GII/GII-2013#43]
Dirección repositorio y documentación(README.md):
<a> https://github.com/javierGaliana/Practica1 </a>

Dirección de la aplicación:
<a>http://periodico.gopagoda.com/  </a>

**Comment by JJ** [comment]
No tienes licencia para imágenes ni textos; ni la has puesto para la aplicación, has incluido ficheros de copia y alguno posiblemente inútil.
