### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by elmendacorp** [IV-GII/GII-2013#45]
Tras mucho pelearme con openshift e intentar montar un juego de la vida en python, y que eso no echaba a andar de ninguna manera me he resignado y he echo esta basurilla.

Repo en Github:
https://github.com/elmendacorp/ivkeygen.git

Web de la app:
http://php-elmendacorp.rhcloud.com/

**Comment by JJ** [comment]
A ver, aparte de las faltas de ortografía y que no has documentado nada, bueno, me vale, pero haberlo intentado con el juego de la vida, hombre...
