### ISSUE TITLE
LeccionesAprendidasPractica1

### ISSUE THREAD

**Issue by elmendacorp** [IV-GII/GII-2013#48]
Poniendo mi granito de arena como alumno de la asignatura, y tras ver las impresiones después de la entrega y evaluación de la practica 1. El problema del alumnado a la hora de usar un lenguaje es el conocimiento previo del mismo, y como alumno me remito al plan de estudios que tenemos, siendo lo mas lejano (académicamente) que hemos llegado a empezar a esbozar "hola mundos" en python, salvo algún alumno que por conocimiento previo supiera otro lenguaje.
Tras mi uso de openshift y herocu, he de decir que un proyecto funcional en cualquier lenguaje que ofrece requiere de una adaptación a la propia plataforma, en cuanto a estructura de directorios y librerías, y creo que eso ha sido lo que ha producido un uso masivo de php, a mi parecer el mas sencillo(adaptación).
Veo interesante, ya que muchos y yo personalmente flojeo, en el tema de licencias y como aplicarlas, lo cual vería interesante un seminario de 30min o así de licencias y su uso en PSL.
Como opinión personal para acabar diré que no estoy acostumbrado tener libertad a la hora de hacer una practica, lo cual esto lo veo mas productivo ya que de la prueba y error se aprende mucho, pero como digo es costumbre. La experiencia ha sido buena.

**Comment by JJ** [comment]
Podemos dar el seminario ese si queréis, por hangout o como sea.

**Comment by JJ** [comment]
Organizado el seminario. El resto, plantéalo en clase o en la lista e iremos tratando de solucionarlo.
