### ISSUE TITLE
CGROUP

### ISSUE THREAD

**Issue by JoSeF267** [IV-GII/GII-2013#5]
He intentado seguir los pasos para crear los grupos de control. Pero al crear la carpeta no introduce ningún tipo de fichero dentro de la misma.ç

Los comandos usados son
 mount -t cgroup cgroup /sys/fs/cgroup

Al realizar este comando me indica que el directorio ya esto montado y no se puede volver a montar.
Pero cuando creo mkdir buenos dentro del directorio creado no me sale los fichero que deben de salir.

**Comment by JJ** [comment]
Por favor, pega los mensajes y uname -a para ver qué kernel y versión del SO usas.

**Comment by JJ** [comment]
¿Puedes probar alguna de las cosas que indican aquí?
http://comments.gmane.org/gmane.linux.kernel.containers.lxc.general/3367

Básicamente, se trata de buscar quién diablos es quien monta /cgroups y eliminarlo (o configurarlo de otra forma)

**Comment by JJ** [comment]
Prueba a usar este programa, cpuset http://code.google.com/p/cpuset/ aunque me imagino que te va a dar el mismo problema...

**Comment by JoSeF267** [comment]
![captura de pantalla de 2013-10-08 21 13 46](https://f.cloud.github.com/assets/487138/1292115/d0896a6e-304e-11e3-8bea-71ea31540be5.png)

Perdón por contestar tan tarde pero no había visto los mensajes le adjunto la pantalla de captura. También he realizado lo que me ponía en las paginas web y me he descargado el programa y sigue me sigue dando los mismos errores.

**Comment by JJ** [comment]
¿Puedes probar a editar el fichero de configuración `/etc/cgconfig.conf` para establecer las reglas desde ahí en vez de desde la línea de órdenes? Desde ahí puedes crear grupos y demás. Aparentemente, algún programa ha montado cgroup y no puedes usarlo de otra forma.

**Comment by JJ** [comment]
¿Cerramos este issue? ¿Lo has probado?
