### ISSUE TITLE
Entrega práctica 2

### ISSUE THREAD

**Issue by PSanchezR** [IV-GII/GII-2013#52]
Hola Juan Julián, en este issue le adjunto la url de mi segunda práctica de este curso:

https://github.com/PSanchezR/practica2/wiki/README

https://github.com/PSanchezR/practica2/wiki/index.php

Gracias por su atención y un saludo.

**Comment by PSanchezR** [comment]
He incluido los cambios para que Schroot no de error, y también he añadido un apartado en README.md con todos los problemas que he tenido a la hora de realizar la práctica

**Comment by oskyar** [comment]
Tienes mal el enlace para ir a tu práctica.

**Comment by JJ** [comment]
+1 para el Óscar, así me gusta, que miréis las prácticas de otros.

**Comment by PSanchezR** [comment]
Muchas gracias Óscar, ya lo he actualizado para que valla directamente al README

**Comment by JJ** [comment]
¡Vaya!

El 9 de noviembre de 2013 10:48, PSanchezR notifications@github.comescribió:

> Muchas gracias Óscar, ya lo he actualizado para que valla directamente al
> README
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/52#issuecomment-28123723
> .

## 

JJ

**Comment by PSanchezR** [comment]
Hay algún problema JJ?

**Comment by oskyar** [comment]
Es porque has escrito vaya con dos eles.

**Comment by PSanchezR** [comment]
Cierto, grave error mio.

**Comment by JJ** [comment]
Poned también la etiqueta Question

**Comment by JJ** [comment]
Bien por los comentarios sobre los problemas encontrados.
