### ISSUE TITLE
Jailkit + jdk + maven2

### ISSUE THREAD

**Issue by oskyar** [IV-GII/GII-2013#53]
Muy buenas, estoy intentando instalar en Jailkit maven2 + jdk para que funcione mi práctica realizada en la práctica1. Pero... me da muchos errores de librerías en jailkit diciéndome que no pueden usar librerías compartidas, etc, etc...

¿Qué puedo hacer entonces? ¿Sigo intentándolo? ó ¿intento hacerlo con un sistema mínimo + chroot ?

Un saludo.

**Comment by JJ** [comment]
¿Por qué no lo intentas simplemente usando chroot a la jaula e instalando cosas? No hace falta que lo instales todo con jailkit, úsalo sólo para el sistema mínimo. jailkit lo único que hace es ayudar a ciertas tareas administrativas de jaulas chroot.

**Comment by oskyar** [comment]
Aaah vale... porque como siempre... ya me estaba complicando la vida, jaja. Si es solo con un sistema minimal, con debootstrap y poco más estará funcionando la jaula.

A ver si lo soluciono esta noche.

**Comment by JJ** [comment]
Si está solucionado, ¿cerramos?
