### ISSUE TITLE
Error al montar el sistema de ficheros virtual

### ISSUE THREAD

**Issue by franciscomanuel** [IV-GII/GII-2013#6]
He intentado seguir los pasos para crear un grupo de control. Al intentar montarlo me dice que ya esta montado y cuando intento crear un nuevo grupo me lo crea vacío.

**Comment by torresj** [comment]
Yo tuve problemas parecidos y opte por crear y gestionar los grupos usando la biblioteca libcgroup. Al instalarla 
ya no tienes que preocuparte de montar o desmontar los cgroups. Yo tengo ubuntu 13.04 y siempre me sale en /sys/fs/cgroup   . Cuando uses la orden cgcreate, en funcion de los parametros que le pongas se te creara una subcarpeta con el nombre del grupo. por ejemplo si pones sudo cgcreate -a jaime -g memory,cpu,cpuacct:ejercicio se te va a crear dentro de memory una carpeta llamada ejercicio, otra de igual nombre dentro de cpu y asi sucesivamente.

**Comment by JJ** [comment]
Por favor, mirad el #5 que tiene el mismo problema.
