### ISSUE TITLE
Práctica 2

### ISSUE THREAD

**Issue by rogegg** [IV-GII/GII-2013#65]
Documentación:

> [https://github.com/rogegg/IV_Practica2/blob/master/Doc.md](https://github.com/rogegg/IV_Practica2/blob/master/Doc.md)

Repositorio de GitHub:

> [https://github.com/rogegg/IV_Practica2](https://github.com/rogegg/IV_Practica2)

**Comment by JJ** [comment]
debootstrap lleva una t, como boot
podéis acceder a los usuarios con su - , no hace falta ssh; no es una máquina virtual, sino una jaula

l
