### ISSUE TITLE
Ejercicio 8 parte 3

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#7]
He supuesto que el ejercicio se puede hacer crando dos grupos, uno en el que se limite el uso a na cpu y otro en el que se limite el uso a la otra cpu (En mi caso tengo dos cpus). Para establecer esa restricción he encontrado que hay que editar el archivo que se encuentra en cpuset/cpuset.cpus en el cual hay que poner la cpu que se quiere usar (0,1,2,...) el problema está en que no consigo editar ese archivo ni con un editor ni usando echo ni con permisos de superusuario... nada. Quizas es que lo he entendido mal y ese archivo no se puede editar...

**Comment by JJ** [comment]
¿Has probado a escribir directamente encima usando redirección? Es decir, >

El 8 de octubre de 2013 19:00, Jaime notifications@github.com escribió:

> He supuesto que el ejercicio se puede hacer crando dos grupos, uno en el
> que se limite el uso a na cpu y otro en el que se limite el uso a la otra
> cpu (En mi caso tengo dos cpus). Para establecer esa restricción he
> encontrado que hay que editar el archivo que se encuentra en
> cpuset/cpuset.cpus en el cual hay que poner la cpu que se quiere usar
> (0,1,2,...) el problema está en que no consigo editar ese archivo ni con un
> editor ni usando echo ni con permisos de superusuario... nada. Quizas es
> que lo he entendido mal y ese archivo no se puede editar...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7
> .

## 

JJ

**Comment by torresj** [comment]
si y me dice permiso denegado (pese a que estoy como root)

**Comment by JJ** [comment]
¿Un copy/paste o captura para que veamos exactamente qué pasa?

El 8 de octubre de 2013 19:06, Jaime notifications@github.com escribió:

> si y me dice permiso denegado (pese a que estoy como root)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25908632
> .

## 

JJ

**Comment by JJ** [comment]
En todo caso, depende de cómo hayas creado o configurado el grupo; tienes
que haberlo hecho para que permita cambiar los cpusets.

El 8 de octubre de 2013 19:08, JJ Merelo jjmerelo@gmail.com escribió:

> ¿Un copy/paste o captura para que veamos exactamente qué pasa?
> 
> El 8 de octubre de 2013 19:06, Jaime notifications@github.com escribió:
> 
> si y me dice permiso denegado (pese a que estoy como root)
> 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25908632
> > .
> 
> ## 
> 
> JJ

## 

JJ

**Comment by torresj** [comment]
![captura de pantalla de 2013-10-08 19 15 34](https://f.cloud.github.com/assets/5519161/1291143/82420cd2-303d-11e3-85bc-bc4c3d3da078.png)

**Comment by JJ** [comment]
ls -alt, ¿por favor?

2013/10/8 Jaime notifications@github.com

> [image: captura de pantalla de 2013-10-08 19 15 34]https://f.cloud.github.com/assets/5519161/1291143/82420cd2-303d-11e3-85bc-bc4c3d3da078.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25909508
> .

## 

JJ

**Comment by torresj** [comment]
![captura de pantalla de 2013-10-08 19 22 20](https://f.cloud.github.com/assets/5519161/1291194/377d9896-303e-11e3-8720-1375c646aa52.png)

**Comment by JJ** [comment]
He encontrado esto:

```
Note that cpusets follow certain rules. For example, children can only
```

include CPUs that the parents already have. If you do not follow those
rules, the kernel cpuset subsystem will not let you create that cpuset. For
example, if you create a cpuset that contains CPU3, and then attempt to
create a child of that cpuset with a CPU other than 3, you will get an
error, and the cpuset will not be active. The error is somewhat cryptic in
that it is usually a "Permission denied" error.

aquí:
https://rt.wiki.kernel.org/index.php/Cpuset_Management_Utility/set_writeup

En todo caso, veo que usas el subdir cpuset. ¿Por qué no creas ejemplo
dentro de `/sys/fs/cgroup` directamente?

2013/10/8 Jaime notifications@github.com

> [image: captura de pantalla de 2013-10-08 19 22 20]https://f.cloud.github.com/assets/5519161/1291194/377d9896-303e-11e3-8720-1375c646aa52.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25909923
> .

## 

JJ

**Comment by torresj** [comment]
no soy yo, es la libcgroup que al usar la orden cgcreate lo hace asi. Si creo yo con mkdir una carpeta dentro de cgroups dentro no tiene nada

**Comment by JJ** [comment]
¿Has hibernado el ordenador?
Fíjate en este error https://bugzilla.redhat.com/show_bug.cgi?id=813228

2013/10/8 Jaime notifications@github.com

> no soy yo, es la libcgroup que al usar la orden cgcreate lo hace asi. Si
> creo yo con mkdir una carpeta dentro de cgroups dentro no tiene nada
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25911316
> .

## 

JJ

**Comment by torresj** [comment]
no, ademas he probado a reiniciar pero me pasa lo mismo... voy a ver si encuentro algo en internet

**Comment by JJ** [comment]
Si todo falla... pregunta en AskUbuntu o StackOverflow (que es lo mismo).
Por cierto, esto lo haces porque, como a otros compañeros, no te funcionaba
trabajar directamente con los grupos ¿no?

2013/10/8 Jaime notifications@github.com

> no, ademas he probado a reiniciar pero me pasa lo mismo... voy a ver si
> encuentro algo en internet
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25912499
> .

## 

JJ

**Comment by torresj** [comment]
si, exacto

**Comment by JJ** [comment]
También puede que sea parte del mismo problema. ¿Sólo te funciona mal el
cpuset o también el resto de las cosas, como cpubandwidth?

2013/10/8 Jaime notifications@github.com

> si, exacto
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25912912
> .

## 

JJ

**Comment by JJ** [comment]
Y también puede ser que sólo puedas poner el cpuset desde el fichero de
configuración. Mira esta presentación
www.haifux.org/lectures/299/netLec7.pdf

El 8 de octubre de 2013 20:00, JJ Merelo jjmerelo@gmail.com escribió:

> También puede que sea parte del mismo problema. ¿Sólo te funciona mal el
> cpuset o también el resto de las cosas, como cpubandwidth?
> 
> 2013/10/8 Jaime notifications@github.com
> 
> > si, exacto
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25912912
> > .
> 
> ## 
> 
> JJ

## 

JJ

**Comment by torresj** [comment]
Justo estoy intentando ahora hacer con el fichero de configuracion a ver si funciona

**Comment by torresj** [comment]
¿hay que activar algo para que use ese el archivo de configuracion?

**Comment by JJ** [comment]
Si arrancas seguro que lo pilla...

**Comment by torresj** [comment]
Con el archivo de configuracion no me da errores

**Comment by JJ** [comment]
¿Y pone las CPU de forma apropiada? Si es así cierra el issue.

2013/10/8 Jaime notifications@github.com

> Con el archivo de configuracion no me da errores
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/7#issuecomment-25914391
> .

## 

JJ

**Comment by torresj** [comment]
Si, muchas gracias
