### ISSUE TITLE
Práctica 2

### ISSUE THREAD

**Issue by elmendacorp** [IV-GII/GII-2013#71]
repo: https://github.com/elmendacorp/practica2IV
Memoria: https://github.com/elmendacorp/practica2IV/wiki/docu

**Comment by JJ** [comment]
Será todo lo trivial que quieras, ¡pero yo tengo que comprobar que has hecho la práctica!

**Comment by elmendacorp** [comment]
No se, con pedir unas capturas, las tengo hechas...

**Comment by JJ** [comment]
En la práctica es donde tienes que enviarlas, precisamente...

**Comment by elmendacorp** [comment]
Añadidas las capturas a la documentación, supuse que con poner el código suficiente. sorry

**Comment by JJ** [comment]
Por favor, lee el guión de la práctica.

**Comment by JJ** [comment]
Simplemente recordarte que hoy acaba el segundo plazo de entrega de esta práctica.
