### ISSUE TITLE
Práctica 2 

### ISSUE THREAD

**Issue by javiercollado** [IV-GII/GII-2013#72]
Aquí está el repositorio creado para la práctica 2:
[Repositorio](https://github.com/javiercollado/practica2JCL)  
Aquí esta la documentación:
[Documentación](https://github.com/javiercollado/practica2JCL/blob/master/practica2.md)

**Comment by JJ** [comment]
No muestras que el resultado funciona con una captura o similar.

**Comment by javiercollado** [comment]
Las capturas de la sección "aplicación desarrollada" son de la aplicación funcionando con la jaula (ejemplo aplicación). Por eso no volví a ponerlas abajo, para no repetirlo. Quizás me falto explicar que era eso.

**Comment by JJ** [comment]
Pero tienes que mostrar en la barra de URLs, al menos, que es el efectivamente la aplicación funcionando en la jaula. De todas formas el punto menos es por una combinación de cosas, no sólo por eso.

**Comment by javiercollado** [comment]
De acuerdo. De todas maneras he modificado documento con la captura.
