### ISSUE TITLE
Problema con cgroups

### ISSUE THREAD

**Issue by oskyar** [IV-GII/GII-2013#8]
Buenas, tengo un problema al ejecutara los grupos con cgroups.
Primero creo un grupo así

> sudo cgcreate -a oskyar -g memory,cpu,cpuacct:navegador

Y después lo ejecuto así

> sudo cgexec -g memory,cpu,cpuacct:navegador firefox

y me salta este error

>  IBUS-WARNING **: The owner of /home/oskyar/.config/ibus/bus is not root!

He buscado por internet pero las respuestas que dan no me satisfacen. Vaya.. que he probado algunas soluciones y no me han dado resultado.

**Comment by JJ** [comment]
Bueno, es un warning, no un error. Yo creo que no tiene nada que ver con
cgexec. En todo caso, debería de funcionar: mira en los directorios
correspondientes y verás como funciona correctamente.

El 9 de octubre de 2013 02:39, Óscar Zafra notifications@github.comescribió:

> Buenas, tengo un problema al ejecutara los grupos con cgroups.
> Primero creo un grupo así
> 
> sudo cgcreate -a oskyar -g memory,cpu,cpuacct:navegador
> 
> Y después lo ejecuto así
> 
> sudo cgexec -g memory,cpu,cpuacct:navegador firefox
> 
> y me salta este error
> 
> IBUS-WARNING **: The owner of /home/oskyar/.config/ibus/bus is not root!
> 
> He buscado por internet pero las respuestas que dan no me satisfacen.
> Vaya.. que he probado algunas soluciones y no me han dado resultado.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/8
> .

## 

JJ

**Comment by oskyar** [comment]
No he dicho nada, anoche llevaba una empanadilla mental.

Gracias.
