### ISSUE TITLE
Mejoras script objetivos. @josemlp91 y @anaprados 

### ISSUE THREAD

**Issue by oskyar** [IV-GII/GII-2013#85]
Se podría hacer que en el parámetro del número de los objetivos que quieres descargar, si pones una "a" (all) te descargue todos los objetivos a la vez junto con la cabecera (Lo de la cabecera es opcional xD).
O intentar que coja varios números en plan array.

Para esto último para no complicarse tanto la vida se podría dejar el parámetro de los objetivos de la sesión para el último, entonces si el programa tiene. 

> $ ./1o file sesion objetivo url

lo dejaría cómo 

> $ ./1o file sesion url objetivo1 objetivo2 objetivo3

¿Cómo lo veis?
Solo doy sugerencias :dancer:

**Comment by oskyar** [comment]
Ó más fácil, si no existe el parámetro 4 pues que añada todos en vez de poner una "a"

**Comment by JJ** [comment]
¿No sería mejor otro script? Este es 1o, de un solo objetivo. Casi mejor
hacer otro ao, all-objetivos, ¿no?

**Comment by oskyar** [comment]
Mmmm... ¿para qué más script? ¿pudiendo añadirle un parámetro más? 
Ya que si se hace mejora en uno, habrá que hacérselas al otro, ¿no?

**Comment by JJ** [comment]
Habría que cambiar los parámetros de sitio (poner el número de objetivo el
último) y no me hace mucha gracia cambiar el API, pero bueno, si hay que
hacerlo mejor ahora que más adelante...

JJ

**Comment by JJ** [comment]
Lo voy a cerrar; creo que se va a quedar como está. Si te animas como scriptero oficial de la asignatura, adelante.
