### ISSUE TITLE
Error con fedora

### ISSUE THREAD

**Issue by JoSeF267** [IV-GII/GII-2013#87]
![error-fedora](https://f.cloud.github.com/assets/487138/1549030/2a1fe982-4ddb-11e3-962f-32f444f74f0a.png)

**Comment by rafaelgonz** [comment]
en lugar de fedora, he instalado centos, y con este tutorial va de maravilla:

http://www.bonusbits.com/main/HowTo:Setup_CentOS_LXC_Container_on_Ubuntu

**Comment by oskyar** [comment]
:+1: Pues voy a seguir tu consejo e instalaré centos en vez de fedora, ya he perdido demasiado tiempo hoy.

**Comment by JJ** [comment]
Creo que adaptaré los apuntes si a todo el mundo le funciona mal Fedora.

JJ

**Comment by oskyar** [comment]
+1. Pero me he dado cuenta que con el script de centos me da también problemas como con Fedora. Yo creo que se debe a tener como host Ubuntu 13.10. Tiene que haber algún tipo de incompatibilidad con el lxc

**Comment by JJ** [comment]
Tened en cuenta que tienen que usar el mismo kernel, igual que pasa con las
jaulas. Si el kernel es demasiado moderno para que lo use Fedora, no va a
funcionar.

**Comment by oskyar** [comment]
Cómo sabemos el kernel que tiene que utilizar fedora? Para intentar
descargarmelo y probarlo.

**Comment by JJ** [comment]
Evidentemente, otro :-)

El problema es que las Fedora "modernas" no funcionan, y el kernel de las
13.xx es demasiado moderno para las que sí funcionan, creo. A partir del
3.6 hubo muchos cambios.

**Comment by josecolella** [comment]
Profesor, no se si ese es el problema, porque me ha funcionado a mi. Aunque tengo Ubuntu 12.04, el kernel que tengo es 3.8

**Comment by oskyar** [comment]
He intentado instalar el kernel 3.0.8-31-generic en Ubuntu 13.10 pero no me carga las interfaces de red (en concreto WLAN, que es indispensable).

Así que he pasado a instalar [Gentoo](https://raw.github.com/globalcitizen/lxc-gentoo/master/lxc-gentoo) que ya lo he probado y me funciona perfectamente, es un template para lxc pero tiene el inconveniente que no se crea con lxc-create, se crea directamente usando el script que se descarga (Que debemos colocar en `/usr/share/lxc/templates/`) pero para lanzar el contenedor si se usa lxc-start con los respectivos parámetros.

Otro inconveniente es que mediante el WebPanel no se ve el contenedor pero eso es cuestión de mover un archivo a un directorio en concreto (que no recuerdo ahora mismo cuál es ni en dónde se coloca, aunque lo documentaré también para que funcione con webpanel (si lo consigo)).

En cuanto termine de documentar el ejercicio pongo el enlace.

Un saludo.

**Comment by JJ** [comment]
Muchas gracias, Óscar.

**Comment by JJ** [comment]
El problema es con las versiones de ubuntu mayores que la 12.04; a mi acaba de instalarme una Fedora 14 en la 12.04 sin problemas.

**Comment by JJ** [comment]
Cuando sean errores en los apuntes, por favor ponedlos en http://github.com/JJ/IV para que pueda cerrarlos con el commit.

**Comment by oskyar** [comment]
De nada, para eso estamos.
