### ISSUE TITLE
Problema con Juju en 13.10 Ubuntu @jj

### ISSUE THREAD

**Issue by oskyar** [IV-GII/GII-2013#88]
Pongo tu usuario en el titulo porque con la aplicación de github en Android no me sale tu usuario. 

Tengo problemas con juju-core desde los repositorios que pusiste. Me metí en la página de juju (luego la pongo desde el portátil) y me descargué la versión para el Ubuntu saucy pero al parecer esa versión no tiene las opciones que indicas en los apuntes de clase. No existe la opción -w y para crear el archivo de configuración no basta con juju unit, hay que añadirle la opción -f 

Después intenté usar juju bootstrap, se queda un rato pensando o haciendo cosas pero no tiene ningún tipo de salida ni de error ni nada. (Antes modifiqué el archivo  de configuración). Ejecuto el siguiente comando para ver el machine y demás, pero no indica ninguna ip para acceder desde el navegador. 

(siento las faltas y demás, estoy desde el móvil)

**Comment by JJ** [comment]
Tienes toda la razón, en mi instalación tiene el mismo problema. Voy a cambiar los apuntes.

**Comment by JJ** [comment]
Aquí comentan el bug en la documentación; de hecho parece que era por la versión que yo tenía instalada, porque en la aclaración sí estaba bien https://bugs.launchpad.net/ubuntu/+source/urlgrabber/+bug/1200288

**Comment by JJ** [comment]
¿Has seguido el resto de las instrucciones, configurar el provider e instalar MongoDB?

**Comment by oskyar** [comment]
Instale mongodb pero al parecer no me di cuenta de que falló la
instalación. Lo he vuelto a instalar y ya si arranca. Pero de todos modos
me siguen sin salir las ips para ver la página de mediawiki.

**Comment by JJ** [comment]
¿Qué te dice `juju status`?

**Comment by oskyar** [comment]
A ver... tengo mis dudas.
1. Nosotros instalamos juju y después cambiamos en el archivo de configuración `default: amazon`  por `default: local` 
2. Ahora ejecutamos `juju switch amazon`
3. Pero en este caso al hacer `juju bootstrap` me sale lo siguiente:

> ERROR environment has no access-key or secret-key

Y si lo hago con `juju switch local`, sí se crea bien el entorno y me deja desplegar lo demás:

> $ juju deploy mediawiki
> $ juju deploy mysql

NOTA: Si añadimos la relación así, `juju add-relation mediawiki mysql` nos mostrará el siguiente error:

> ERROR ambiguous relation: "mediawiki mysql" could refer to "mediawiki:db mysql:db"; "mediawiki:slave mysql:db"

Por lo que yo añado la relación así: `juju add-relation mediawiki:db mysql`

Ahora expongo mediawiki: `juju expose mediawiki`

pero a la hora de ejecutar `status` sale lo siguiente:

> environment: local
> machines:
>   "0":
>     agent-state: started
>     agent-version: 1.16.3.1
>     dns-name: 10.0.3.1
>     instance-id: localhost
>     series: saucy
>   "1":
>     agent-state-info: '(error: container "oskyar-local-machine-1" is already created)'
>     instance-id: pending
>     series: precise
>   "2":
>     agent-state-info: '(error: container "oskyar-local-machine-2" is already created)'
>     instance-id: pending
>     series: precise
> services:
>   mediawiki:
>     charm: cs:precise/mediawiki-10
>     exposed: true
>     relations:
>       db:
>       - mysql
>     units:
>       mediawiki/0:
>         agent-state: pending
>         machine: "1"
>   mysql:
>     charm: cs:precise/mysql-29
>     exposed: false
>     relations:
>       cluster:
>       - mysql
>       db:
>       - mediawiki
>     units:
>       mysql/0:
>         agent-state: pending
>         machine: "2"

Así que... como no me sale ninguna ip ni nada, no puedo verlo desde el navegador y ya he hecho la instalación, despliegue y demás unas cuantas veces.

**Comment by JJ** [comment]
Hay algún problema porque el status pone pending...

El lunes, 18 de noviembre de 2013, Óscar Zafra notifications@github.com
escribió:

> A ver... tengo mis dudas.
> 1. Nosotros instalamos juju y después cambiamos en el archivo de
> configuración default: amazon por default: local
> 2. Ahora ejecutamos juju switch amazon
> 3. Pero en este caso al hacer juju bootstrap me sale lo siguiente:
> 
> ERROR environment has no access-key or secret-key
> 
> Y si lo hago con juju switch local, sí se crea bien el entorno y me deja
> desplegar lo demás:
> 
> $ juju deploy mediawiki
> $ juju deploy mysql
> 
> NOTA: Si añadimos la relación así, juju add-relation mediawiki mysql nos
> mostrará el siguiente error:
> 
> ERROR ambiguous relation: "mediawiki mysql" could refer to "mediawiki:db
> mysql:db"; "mediawiki:slave mysql:db"
> 
> Por lo que yo añado la relación así: juju add-relation mediawiki:db mysql
> 
> Ahora expongo mediawiki: juju expose mediawiki
> 
> pero a la hora de ejecutar status sale lo siguiente:
> 
> environment: local
> machines:
> "0":
> agent-state: started
> agent-version: 1.16.3.1
> dns-name: 10.0.3.1
> instance-id: localhost
> series: saucy
> "1":
> agent-state-info: '(error: container "oskyar-local-machine-1" is already
> created)'
> instance-id: pending
> series: precise
> "2":
> agent-state-info: '(error: container "oskyar-local-machine-2" is already
> created)'
> instance-id: pending
> series: precise
> services:
> mediawiki:
> charm: cs:precise/mediawiki-10
> exposed: true
> relations:
> db:
> - mysql
>   units:
>   mediawiki/0:
>   agent-state: pending
>   machine: "1"
>   mysql:
>   charm: cs:precise/mysql-29
>   exposed: false
>   relations:
>   cluster:
> - mysql
>   db:
> - mediawiki
>   units:
>   mysql/0:
>   agent-state: pending
>   machine: "2"
> 
> Así que... como no me sale ninguna ip ni nada, no puedo verlo desde el
> navegador y ya he hecho la instalación, despliegue y demás unas cuantas
> veces.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

JJ

**Comment by torresj** [comment]
a mi me pasaba lo mismo que a ti oscar, pero al reiniciar ya me sale:

jaime@jaime-VGN-FZ21E:~$ juju status
environment: local
machines:
  "0":
    agent-state: started
    agent-version: 1.16.3.1
    dns-name: 10.0.3.1
    instance-id: localhost
    series: saucy
  "1":
    agent-state-info: '(error: container "jaime-local-machine-1" is already created)'
    instance-id: pending
    series: precise
  "2":
    agent-state: started
    agent-version: 1.16.3.1
    instance-id: jaime-local-machine-2
    instance-state: missing
    series: precise
  "3":
    agent-state: pending
    instance-id: jaime-local-machine-3
    instance-state: missing
    series: precise
services:
  mediawiki:
    charm: cs:precise/mediawiki-10
    exposed: true
    relations:
      slave:
      - mysql
    units:
      mediawiki/0:
        agent-state: pending
        machine: "3"
  mysql:
    charm: cs:precise/mysql-29
    exposed: false
    relations:
      cluster:
      - mysql
      db:
      - mediawiki
      - wordpress
    units:
      mysql/0:
        agent-state: pending
        agent-version: 1.16.3.1
        machine: "2"
        public-address: 10.0.3.78
  wordpress:
    charm: cs:precise/wordpress-20
    exposed: false
    relations:
      db:
      - mysql
      loadbalancer:
      - wordpress
    units:
      wordpress/0:
        agent-state: pending
        machine: "1"

**Comment by oskyar** [comment]
Pues entonces no sé que hacer ya... (expongo de nuevo los pasos).
Dejo todo desde 0:
sudo juju destroy-environment

Comienzo todo:

```
sudo juju switch local
sudo juju bootstrap
sudo juju deploy mediawiki
sudo juju deploy mysql
sudo juju add-relation mediawiki:slave mysql:db
sudo juju expose mediawiki

sudo juju status
```

> environment: local
> machines:
>   "0":
>     agent-state: started
>     agent-version: 1.16.3.1
>     dns-name: 10.0.3.1
>     instance-id: localhost
>     series: saucy
>   "1":
>     instance-id: pending
>     series: precise
>   "2":
>     instance-id: pending
>     series: precise
> services:
>   mediawiki:
>     charm: cs:precise/mediawiki-10
>     exposed: true
>     relations:
>       slave:
>       - mysql
>     units:
>       mediawiki/0:
>         agent-state: pending
>         machine: "1"
>   mysql:
>     charm: cs:precise/mysql-29
>     exposed: false
>     relations:
>       cluster:
>       - mysql
>       db:
>       - mediawiki
>     units:
>       mysql/0:
>         agent-state: pending
>         machine: "2"

Y en verdad... ya no sé qué más hacer... ¿Alguna sugerencia?

**Comment by torresj** [comment]
Yo lo que no consigo es que me funcione es sudo juju expose mediawiki.
Me pone siempre "exposed:false" como puede verse en mi anterior comentario

**Comment by JJ** [comment]
¿Por qué pones mediawiki:slave y no mediawiki:db?

**Comment by JJ** [comment]
En este documento dice que hagas lo que hiciste al principio
https://juju.ubuntu.com/docs/charms-relations.html

juju add-relation mediawiki:db mysql

**Comment by JJ** [comment]
Efectivamente, figura mediawiki como slave pero tendría que figurar como conectado a la bd.

**Comment by JJ** [comment]
En el repo del _charm_ correspondiente viene alguna explicación más sobre como usarlo https://github.com/charms/mediawiki

**Comment by oskyar** [comment]
Pues lo he vuelto a intentar y sigue sin funcionar. El viernes lo vemos mejor en clase que ya le he echado demasiadas horas a este ejercicio...

**Comment by JJ** [comment]
OK

**Comment by JJ** [comment]
Pero ¿has probado lo que te he dicho?

```
sudo juju add-relation mediawiki:db mysql
```

Eso en vez de la orden `add-relation` que has puesto.

**Comment by oskyar** [comment]
Si, he probado to toíco to y no hay manera. He desactivado el firewall , de
todo...

**Comment by JJ** [comment]
¿Y no puede ser un problema con la máquina virtual que hayas instalado?
¿has probado con otra?

## 

JJ

**Comment by JJ** [comment]
¿Qué versión de kernel es?

**Comment by JJ** [comment]
Me está dando el mismo problema. A ver si lo puedo solucionar.

JJ

**Comment by JJ** [comment]
Me parece que es porque el contenedor no está funcionando. ¿Has probado a
conectarte al contenedor creado y a ver su estado?

**Comment by oskyar** [comment]
es decir, ¿que me meta dentro de un contenedor y haga un juju status ? ¿No se supone que juju se instala en el host? Voy a probar a ver...

**Comment by oskyar** [comment]
Al hacer juju bootstrap se supone que crea una máquina en mi caso 'oskyar-local-machine-1' pero... no me la crea en lxc porque dice que ya existe... voy a borrarla manualmente a ver si así me la crea desde 0.

**Comment by JJ** [comment]
Bórrala con lxc destroy

De todas formas, me da la impresión de que es un poco buggy...

**Comment by oskyar** [comment]
Si... borro el entorno `sudo juju destroy-environment`
Y también lo borro mediante `sudo lxc-destroy contenedor` 

Pero hay archivos que los deja almacenados, tales como las configuraciones de cgroups y logs.

¿Qué es buggy?

**Comment by JJ** [comment]
Con errores.

## 

JJ

**Comment by oskyar** [comment]
Ah vale, conozco el término `bug` pero buggy no xD. Pues... lo miramos mañana en clase mejor?

Un saludo.

**Comment by JJ** [comment]
OK.

JJ

**Comment by JJ** [comment]
También puedes probar a ver si es cosa de Wikimedia o de cualquier otra instalación...

**Comment by oskyar** [comment]
Que va, habré instalado 20 veces los contenedores, intenté instalar
WordPress y tampoco... He llegado a ocupar 10 gigas entre instalaciones,
contenedores y demás.

**Comment by JJ** [comment]
Una prueba más: http://askubuntu.com/questions/134977/juju-stuck-in-pending-state-when-using-lxc

Lo que ocupa un mogollón es MongoDb, que se pilla para él solito un mongón de gigas :-)

**Comment by torresj** [comment]
Mi portatil tuvo un problema grave y he tenido que formatearlo, al instalar otra vez ubuntu y descargar juju me pasa lo mismo que a oscar. Como no me funciona no puedo poner capturas de pantalla en los ejercicios aunque antes de formatear si que me funcionaba juju (como pudiste ver en clase) y pude probar todos los comandos de los ejercicios con exito. No se muy bien por qué pero ahora no hay manera...

**Comment by JJ** [comment]
Da algún detalle máa aunque estoy por dejar juju como caso perdido. Intenta también poner un issue en el propio juju a ver si allí te pueden ayudar.

**Comment by torresj** [comment]
Me pasa como a oscar, las maquinas salen en pending siempre... Yo lo he dado por perdido ya porque no he conseguido que funcione

**Comment by oskyar** [comment]
Pues yo hoy he tenido mi día esplendido jajaja.
A mi me ha funcionado todo. (Claro está que después de tener que formatear
dos veces).
Ahora después termino de añadir los enlaces a mis archivos.

Eso si Jaime, he sido paciente y he dejado un rato los servicios y han
pasado de pending a started.

La instalación de juju ha sido mediante los repositorios de la guía de @jj
y la instalación de lo demás mediante apt-get.

Un saludo.

**Comment by oskyar** [comment]
Coge el script de mi repositorio llamado scriptJuju.sh y ponle como
parametro crear.

```
./scriptJuju crear
```

Si te da errores borra todo con

```
./scriptJuju destruir
```

(el script es solo cuando has instalado el entorno con los servicios
mediawiki y MySQL, añades la relación y expones mediawiki)

Pero no pierdes nada probándolo xD.

Un saludoo

**Comment by torresj** [comment]
tengo el script igual k tu, y nada... da igual si antes de formatear me iba perfecto y pude hacerlo todo lo que pasa es que no hice las capturas

**Comment by antonioguirola** [comment]
A mí en Ubuntu 12.04 también me pasa el problema de que las máquinas se quedan en 'pending' siempre...

**Comment by germaaan** [comment]
Yo tengo Ubuntu 13.10 y también me daba siempre el problema del "pending" hiciera lo que hiciera, hasta que por probar cogí destruí todo con "juju destroy-environment" y empecé a volver a hacerlo paso por paso, pero esta vez dejando unos 10 minutos entre acción y acción porque se veía que el ordenador estaba "trabajando" en algo todavía, que los comandos son los mismos que vienen en los apuntes:

juju bootstrap
juju deploy mediawiki
juju deploy mysql
juju add-relation mediawiki:db mysql
juju expose mediawiki

No sé si sería casualidad, pero dejando ese tiempo entre comando y comando, al final después de esperar por "juju expose mediawiki", en el "juju status" me aparecía por fin todo como "started".

**Comment by JJ** [comment]
Cierro con el acertado comentario de @germaaan
