### ISSUE TITLE
Problema con lxc web panel

### ISSUE THREAD

**Issue by franvalverde** [IV-GII/GII-2013#89]
He tenido que realizar la instalación de LXC web panel manualmente ya que de la otra forma me fallaba. Basicamente lo que he hecho es clonar un repositorio y lanzar un .py para que se ejecute el web panel. 

El problema es el siguiente; cuando me conecto no me detecta ningun contenedor y tengo varios creados a los cuales puedo acceder desde consola con total normalidad. 

Otro detalle es que cuando intento crear un contenedor desde la misma plataforma web me da el error "Internal Server Error" que tanto adoramos los alumnos que cursamos DAI.

Un saludo y gracias por la atención.

**Comment by oskyar** [comment]
¿Qué errores te da cuando lo vas a instalar? ¿no puedes ejecutar el comando que lo instala automáticamente?

```
wget http://lxc-webpanel.github.io/tools/install.sh -O - | bash
```

Al parecer cuando se crea un contenedor o más bien cuando se instala lxc-webpanel, lee unos archivos de configuración en una carpeta determinada que es donde está la información de los contenedores. Si no se crea la información o no está configurado LWP para leer buscar en esa carpeta los archivos no te van a salir los contenedores instalados.

Un saludo y espero haberte ayudado en algo.

**Comment by oskyar** [comment]
Una última cosa, recuerda que para ejecutar ese comando tienes que ser root (sudo su).

**Comment by JJ** [comment]
@franvalverde mira lo que comenta @oskyar y si te funciona, cierra.

**Comment by franvalverde** [comment]
Si,  si me funciono. No conteste porque yo lo hacia exactamente igual pero el problema era de mi poca paciencia, lo deje, me fui y cuando volvi estaba instalado y ya si muestra los contenedores. 

Gracias
