### ISSUE TITLE
Error al hacer fork

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#9]
Formatee el pc y al intentar hacer una copia del repositorio de la asignatura, copie el de un compañero ,josecolella,su repositorio en vez del de la asignatura. Aunque ya lo he hablado con él quería que se supiera que ha sido por error y no por otros motivos

**Comment by JJ** [comment]
En absoluto ha sido un error. Los repositorios están para eso. ¡Copiad, malditos!
