### ISSUE TITLE
Duda ejercicio 2 virtualicación del almacenamiento

### ISSUE THREAD

**Issue by torresj** [IV-GII/GII-2013#90]
No entiendo la parte "avanzado" que se pide en el ejercicio.¿Sería algo así como programar lo que hace sshfs pero en ruby?es decir¿usando ruby montar un fichero remoto?

**Comment by JJ** [comment]
No, crear en Ruby un programa que "responda" como si se tratara de un filesystem. Es decir, que puedas navegar con él y te muestre recursos (las variables) como si fueran directorios y subdirectorios.

**Comment by torresj** [comment]
Aaaa, vale, perfecto. Muchas gracias
