### ISSUE TITLE
Problemas con Ubuntu (No funciona teclado en terminal y navegador)

### ISSUE THREAD

**Issue by oskyar** [IV-GII/GII-2013#91]
Buenas... tengo un problema y ya estoy desesperaíco...

Anoche estaba usando ubuntu como normalmente, pero cuando he arrancado esta mañana ubuntu de nuevo, el teclado no me funciona, ni en el navegador ni en el terminal. Pero sin embargo, si funciona en los editores de texto ó en la interfaz cuando vas a hacer búsquedas. Pero no entiendo porqué no funciona en el terminal ni en firefox.

Lo único que instalé anoche fue mysql-workbench, pero dudo que sea por eso...
No sé que hacer, ni cómo buscar soluciones al problema porque no sé como explicarlo por google. No encuentro soluciones :'(

**Comment by JJ** [comment]
Estos problemas de "yo no instalé más que no sé qué" normalmente se deben a falta de espacio (y más si lo que has instalado es una base de datos). Yo me iría al terminal normal (Ctrl-alt-f1) e iría viendo los mensajes del sistema con dmesg, lo que hay en los diferentes filesystems con df y demás comprobaciones rutinarias. Si todo eso falla, .Xerrors y finalmente arrancer a prueba de errores.

**Comment by oskyar** [comment]
Espacio tengo porque formatee hace poco para probar de nuevo juju y toso
eso. Y me quedan mas de 10 gigas libres. He conseguido que el terminal por
lo menos me reconozca el teclado, al parecer se ha cambiado solo el método
de entrada y por eso no me detectaba las pulsaciones del teclado. Pero
ahora no se como hacerlo para el navegador.

Gracias por contestar. Un saludo.

**Comment by JJ** [comment]
Prueba alguna de estas cosas (aunque son soluciones para el navegador Tor)
https://trac.torproject.org/projects/tor/ticket/9353
Puede ser un problema de gtk o de ibus, pero tendrías que ver qué es lo que
no funciona, si es sólo el navegador o algún otro programa como el
procesador de textos. De todas formas, asegúrate de que tienes 10G libres
porque es lo que se ventila el MongoDB nada más empezar.

**Comment by oskyar** [comment]
¡¡Gracias @JJ !!, lo he conseguido arreglar...
Aunque lo he arreglado de otra forma, tan solo buscando en los programas de ubuntu `input method` ahí pones el método que quieras de entrada, reinicias y ya me funcionaba.

El problema ha estado seguramente en que me dan mucho corage los warnings y por arreglaro me cargué esto xDD. Al abrir programas cómo gedit desde el terminal, a mi siempre me salta con que el directorio `/home/(usuario)/.config/ibus/bus no es root` entonces anoche precisamente hice un `sudo chown root:root /home/oskyar/.config/ibus/bus` y cuando he ido a hacer mis historias esta mañana con ubuntu no me funcionaba el teclado en el navegador y en el terminal. Yo creo que ha sido precisamente por eso.

Nuevamente gracias.

Un saludo.

**Comment by JJ** [comment]
Por una nota en el wiki de la asignatura o donde quieras contando como lo
has arreglado y enlázala desde aquí, porfa.

**Comment by oskyar** [comment]
:+1: listo.

[Página de problemas](https://github.com/IV-GII/GII-2013/wiki/Problemas-ajenos-a-la-asignatura)
