### ISSUE TITLE
Fichero de configuración de CEPH erroneo

### ISSUE THREAD

**Issue by rafaelgonz** [IV-GII/GII-2013#92]
El fichero de configuración de CEPH está erroneo, ya que no aparecen los corchetes necesarios, cosa que en la web tutorial, si viene.

**Comment by JJ** [comment]
Es de los apuntes, correspondería ponerlo en [los issues de los apuntes](http://github.com/JJ/IV/issues). En todo caso es un error de Markdown que ya está corregido (creo)
