### ISSUE TITLE
Error al montar Ceph

### ISSUE THREAD

**Issue by germaaan** [IV-GII/GII-2013#94]
Cuando intento montar ceph con `sudo mount -t ceph germaaan-pc:/ /mnt/ceph` obtengo como resultado el error `mount error 5 = Input/output error`.

Si consulto las entradas de `dmesg` referentes a ceph solo me aparece: 

```
[18125.363042] libceph: mon0 127.0.1.1:6789 socket error on write
```

También he probado con `sudo mount.ceph germaaan-pc:/ /mnt/ceph`, pero pasa lo mismo.

**Comment by JJ** [comment]
¿Puede ser un problema de acceso? ¿O con la dirección? ¿No debería ser
127.0.0.1?

**Comment by germaaan** [comment]
Eso es lo que me resulta raro, que en el fichero de configuración tengo:

```
[mon.gpc]
    host = germaaan-pc
    mon addr = 127.0.0.1:6789
```

Sin embargo, pone que el error se produce con la dirección 127.0.1.1:6789, coincidiendo el puerto, pero no la dirección que tengo puesta en el archivo de configuración.

**Comment by JJ** [comment]
Tienes que mirar en /etc/hosts a ver qué dirección tiene asignada
germaaan-pc o poner ahí directamente 127.0.0.1

**Comment by germaaan** [comment]
Sí, el problema de la dirección era ese, pero ahora me da otro: `mount error 22 = Invalid argument`

Y en este caso en `dmesg` dice:

```
2013-12-19 20:08:55.910106 7f8d5339c700 -1 monclient(hunting): authenticate NOTE: no keyring found; disabled cephx authentication
2013-12-19 20:08:55.910130 7f8d5339c700  0 librados: client.admin authentication error (95) Operation not supported
```

Pero lo he solucionado desactivando Cephx como indican en su [página](http://ceph.com/docs/master/rados/operations/authentication/), añadiendo las siguientes líneas a la sección [global] del archivo de configuración:

```
    auth cluster required = none
    auth service required = none
    auth client required = none
    auth supported = none
```

![solucion_montado](https://f.cloud.github.com/assets/5518719/1785456/9f0ebb64-68e4-11e3-82f4-1a72900bae71.png)

**Comment by JJ** [comment]
Genial, Germán. Muchas gracias.

**Comment by germaaan** [comment]
Para eso estamos.
