### ISSUE TITLE
Duda sobre almacenar directorios completos usando ceph y rados.

### ISSUE THREAD

**Issue by germaaan** [IV-GII/GII-2013#95]
Almacenar objetos en una piscina es simple con `rados put -p prueba-piscina objeto archivo`, pero no se puede almacenar directorios de la misma forma con `rados put -p prueba-piscina directorio prueba` porque da un error indicando que no se puede porque es un directorio:

error reading input file prueba: (21) Is a directory
error putting prueba-piscina/directorio: Is a directory

No encuentro nada claro sobre como hacerlo, ¿alguna indicación o pista a tener en cuenta por si es que lo estoy planteando mal?

**Comment by JJ** [comment]
En realidad, como muchos ejercicios, no es del tipo de ejercicio que tiene una respuesta correcta, sino que lo planteé a ver qué ideábais. Así que tu solución cuando la tengas es tan buena como otra cualquiera.

**Comment by germaaan** [comment]
Ok, gracias por la aclaración.
