### ISSUE TITLE
Error al crear sistema de ficheros de objetos en CEPH

### ISSUE THREAD

**Issue by rafaelgonz** [IV-GII/GII-2013#96]
Haciendo el ejercicio de CEPH, al intentar crear el sistema de ficheros de objetos con:

sudo /sbin/mkcephfs -a -c /etc/ceph/ceph.conf

me aparece la siguiente salida:

rafael@rafael-eM350:~$ sudo /sbin/mkcephfs -a -c /etc/ceph/ceph.conf
temp dir is /tmp/mkcephfs.NKQEZE9fhc
preparing monmap in /tmp/mkcephfs.NKQEZE9fhc/monmap
/usr/bin/monmaptool --create --clobber --add gpc 127.0.0.1:6789 --print /tmp/mkcephfs.NKQEZE9fhc/monmap
/usr/bin/monmaptool: monmap file /tmp/mkcephfs.NKQEZE9fhc/monmap
/usr/bin/monmaptool: generated fsid 9a38efd3-1ff7-4644-b321-7578eb7ed4ba
epoch 0
fsid 9a38efd3-1ff7-4644-b321-7578eb7ed4ba
last_changed 2013-12-27 09:25:37.793257
created 2013-12-27 09:25:37.793257
0: 127.0.0.1:6789/0 mon.gpc
/usr/bin/monmaptool: writing epoch 0 to /tmp/mkcephfs.NKQEZE9fhc/monmap (1 monitors)
=== osd.0 === 
2013-12-27 09:25:38.225841 b6bad740 -1 filestore(/srv/ceph/osd/osd.0) limited size xattrs -- enable filestore_xattr_use_omap
2013-12-27 09:25:38.225906 b6bad740 -1 OSD::mkfs: couldn't mount FileStore: error -95
2013-12-27 09:25:38.226037 b6bad740 -1  *\* ERROR: error creating empty object store in /srv/ceph/osd/osd.0: (95) Operation not supported
failed: '/sbin/mkcephfs -d /tmp/mkcephfs.NKQEZE9fhc --init-daemon osd.0'

¿A qué se puede deber este error?

gracias a todos de antemano!!!!

**Comment by JJ** [comment]
Puede ser por la configuración del sistema de ficheros, tiene que usar xattr, al parecer, como indica aqui
http://jcftang.github.io/2012/09/04/adding-an-osd-to-a-ceph-cluster/
Aquí también ponen una posible solución http://permalink.gmane.org/gmane.comp.file-systems.ceph.devel/9432
En todo caso, la forma de resolver estos errores es siempre buscar una palabra o palabras significativas en google, usando comillas para acotar: https://www.google.es/search?client=ubuntu&channel=fs&q=enable+filestore_xattr_use_omap&ie=utf-8&oe=utf-8&gws_rd=cr&ei=G2C9UumeO6Sa0AWYmoBA#channel=fs&q=%22enable+filestore_xattr_use_omap%22&safe=off 
Si no funciona, pregunta (en inglés) en StackOverflow y, finalmente, lista de correo o foro de ayuda del paquete correspondiente.
