### ISSUE TITLE
Problema con VNC y KVM/QEMU

### ISSUE THREAD

**Issue by germaaan** [IV-GII/GII-2013#97]
Creo una máquina virtual en KVM/QEMU para instalar Lubuntu para el ejercicio 4, se instala y después funciona perfectamente en el arranque normal:

```
qemu-system-x86_64 -boot order=c -drive file=~/qemu/hdd-lubuntu.img,if=virtio -m 512M -name lubuntu
```

![eje04_img02](https://f.cloud.github.com/assets/5518719/1816320/eff620e4-6f38-11e3-80b5-3dd3cce2911a.png)

Pero si lo arranco para conectar mediante VNC:

```
qemu-system-x86_64 -boot order=c -drive file=~/qemu/hdd-lubuntu.img,if=virtio -m 512M -name lubuntu -vnc :1
```

Cuando intento conetarme con `vinagre lubuntu:5901` me dice "Conexión cerrada. Se cerró la conexión con el equipo lubuntu::5901."

![eje04_img04](https://f.cloud.github.com/assets/5518719/1816319/d19e6ff2-6f38-11e3-9ffd-110f34c99ad0.png)

**Comment by JJ** [comment]
¿Has probado otros puertos?

**Comment by germaaan** [comment]
Sí, por ejemplo "-vnc :0" puerto 5900,  "-vnc :5" puerto 5905 o  "-vnc :10" puerto 5910, y para todos me dice exactamente lo mismo.

**Comment by JJ** [comment]
Prueba a ver si vinagre tiene una opción --verbose para que te vaya
diciendo dónde se rechaza la conexión, si es a nivel de qemu/kvm o de la
propia máquina virtual y las razones.

El 28 de diciembre de 2013, 13:08, German Martinez <notifications@github.com

> escribió:
> 
> Sí, por ejemplo "-vnc :0" puerto 5900, "-vnc :5" puerto 5905 o "-vnc :10"
> puerto 5910, y para todos me dice exactamente lo mismo.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/IV-GII/GII-2013/issues/97#issuecomment-31295414
> .

## 

JJ

**Comment by germaaan** [comment]
Sí, activo la salida de depuración y obtengo lo siguiente:

germaaan@germaaan-pc:~$ vinagre --gtk-vnc-debug lubuntu:5901
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Init VncConnection=0xd848d0
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncdisplaykeymap.c Using evdev keycode mapping
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncdisplay.c Grab sequence is now Control_L+Alt_L
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Open host=lubuntu port=5901
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Open coroutine starting
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Started background coroutine
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Resolving host lubuntu 5901
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Doing final VNC cleanup
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Close VncConnection=0xd848d0
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Emit main context 14
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncdisplay.c Disconnected from VNC server
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncdisplay.c Display destroy, requesting that VNC connection close
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncdisplay.c Display destroy, requesting that VNC connection close
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncdisplay.c Releasing VNC widget
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Delayed unref VncConnection=0xd848d0
(vinagre:23564): gtk-vnc-DEBUG: ../../../src/vncconnection.c Finalize VncConnection=0xd848d0

He googleado un poco, pero no he terminado de encontrar algo que me fuera realmente últi.

**Comment by JJ** [comment]
Yo diría que no encuentra el host. Si no lo tienes en /etc/hosts el
anfitrión no tiene por qué saber que lubuntu es 192.168.0. lo que sea.
Prueba la IP que le asigne automáticamente.

**Comment by germaaan** [comment]
De acuerdo, el problema era ese sí, es que en el enlace del QEMU Emulator User Documentation dice que con la opción "-name nombre" el nombre también se utiliza para el servidor de VNC, aunque no de la forma que yo creía. La dirección a la que hay que conectarse es a la de la interfaz NAT de KVM "virbr0" que en mi caso es "192.168.122.1", así con "vinagre 192.168.122.1:5901" ya si funciona correctamente:

![eje04_img05](https://f.cloud.github.com/assets/5518719/1827025/c70b4ffa-721d-11e3-8b3a-0a257b7fa1ce.png)

Gracias.
