### ISSUE TITLE
Duda sobre práctica 3

### ISSUE THREAD

**Issue by germaaan** [IV-GII/GII-2013#98]
El día que se habló sobre la práctica 3 en clase llegue bastante tarde y al ponerme a hacerla me han surgido dudas.

A ver si lo entiendo, ¿la idea es que pensemos en cualquier tipo de aplicación y diseñemos una máquina virtual a montar para que en ella funcione esa aplicación?

Vamos, lo que podría ser pensar en una aplicación que provea de un servicio al usuario y especificar para ella la carga de trabajo para la que debería estar preparada (mínimo indicando uso de memoria, CPU y almacenamiento), y de entre posibles configuraciones que pudiera realizar para ponerla en funcionamiento, una vez haya montado la aplicación, justificar la que he elegido finalmente.

**Comment by JJ** [comment]
Efectivamente, esa es la idea. Básicamente se trata de que cuando montéis una máquina virtual en Azure o VMWare o lo que sea no lo hagáis en plan "burro grande", sino que la diseñéis con los recursos necesarios, pero sólo esos. También que os acostumbréis, primero, a la flexibilidad que te da esto, que puedes montar una máquina con Ubuntu 13.10, probarla, y tirarla y montar otra en minutos y sobre todo que, con infraestructuras virtuales, es fácil medir en condiciones parecidas qué combinación máquina/sistema operativo/recursos usados por los mismos es la más adecuada para una tarea determinada.

**Comment by germaaan** [comment]
De acuerdo, aclarado eso entonces.

Otro par de cosas más, en cuanto a una máquina virtual local, ¿da igual que sea bajo QEMU, VMM, VirtualBox o cualquier por el estilo? 

Y en cuanto a la aplicación, ¿que sea algo como lo que hemos venido haciendo en las últimas prácticas, o más bien debería ser algo más "elaborado"? Por poner un ejemplo, montar un servicio en una máquina virtual en Azure y realizar una pequeña aplicación que nos permita interaccionar y/o acceder a dicho servicio, porque en este último caso es en el que veo que si tendría sentido tener especial interés en analizar los recursos necesarios para dicha aplicación.

**Comment by JJ** [comment]
Sí, el que mejor manejéis. Podéis usar esa aplicación o crear otra nueva, pero que no sea un "hola mundo"

**Comment by germaaan** [comment]
Ok, pues ya lo tengo todo aclarado. Gracias.
